const MAX=9,cameraPicker=document.getElementById("cameraPicker"),albumPicker=document.getElementById("albumPicker"),photos=document.getElementById("photos"),cameraAdd=document.getElementById("cameraAdd"),albumAdd=document.getElementById("albumAdd"),count=document.getElementById("count"),analyze=document.getElementById("analyze"),result=document.getElementById("result"),fields=document.getElementById("fields");let items=[],lang="sv-SE";
function draw(){photos.replaceChildren();items.forEach((item,i)=>{const d=document.createElement("div");d.className="v-photo";d.innerHTML='<img alt="Bild '+(i+1)+'"><span class="v-photo-number">'+(i+1)+'</span><button type="button" aria-label="Ta bort bild">×</button>';d.querySelector("img").src=item.url;d.querySelector("button").onclick=()=>{URL.revokeObjectURL(item.url);items.splice(i,1);draw()};photos.append(d)});count.textContent=items.length+" / "+MAX;analyze.disabled=!items.length;const full=items.length>=MAX;cameraAdd.disabled=full;albumAdd.disabled=full;document.querySelector(".v-photo-actions")?.classList.toggle("is-full",full)}
function addFiles(files){for(const file of [...(files||[])]){if(items.length>=MAX)break;if(file.type.startsWith("image/"))items.push({file,url:URL.createObjectURL(file)})}draw()}
cameraAdd.onclick=()=>cameraPicker.click();albumAdd.onclick=()=>albumPicker.click();
cameraPicker.onchange=()=>{addFiles(cameraPicker.files);cameraPicker.value=""};
albumPicker.onchange=()=>{addFiles(albumPicker.files);albumPicker.value=""};
document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=()=>{lang=b.dataset.lang;document.querySelectorAll("[data-lang]").forEach(x=>x.classList.toggle("active",x===b))});
const demoSv=[["TITEL","Analys kopplas in i nästa steg","REVIEW"],["BESKRIVNING","Bildflödet verifieras först. Ingen osäker produktinformation visas som fakta.","REVIEW"],["KATEGORI","Kontrollera/fyll i","UNKNOWN"],["MÄRKE","Kontrollera/fyll i","UNKNOWN"],["STORLEK","Kontrollera/fyll i","UNKNOWN"],["SKICK","Kontrollera/fyll i","UNKNOWN"],["FÄRG","Kontrollera/fyll i","UNKNOWN"],["MATERIAL","Kontrollera/fyll i","UNKNOWN"],["PRIS","Prisförslag kopplas in efter verifierad analys","REVIEW"]];
const demoEn=[["TITLE","Analysis will be connected in the next step","REVIEW"],["DESCRIPTION","The photo flow is verified first. No uncertain product information is presented as fact.","REVIEW"],["CATEGORY","Check / fill in","UNKNOWN"],["BRAND","Check / fill in","UNKNOWN"],["SIZE","Check / fill in","UNKNOWN"],["CONDITION","Check / fill in","UNKNOWN"],["COLOUR","Check / fill in","UNKNOWN"],["MATERIAL","Check / fill in","UNKNOWN"],["PRICE","Price suggestion follows verified analysis","REVIEW"]];
function renderFields(rows){fields.replaceChildren();rows.forEach(([label,value,status])=>{const row=document.createElement("div");row.className="v-field";row.innerHTML='<div class="v-field-main"><div class="v-label"><span>'+label+'</span><span class="v-status">'+(status==="UNKNOWN"?(lang==="sv-SE"?"Kontrollera":"Check"):(lang==="sv-SE"?"Förslag":"Suggestion"))+'</span></div><div class="v-value"></div></div><button class="v-copy" type="button" aria-label="Kopiera"><svg viewBox="0 0 24 24"><rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/></svg></button>';row.querySelector(".v-value").textContent=value;const copy=row.querySelector(".v-copy");copy.onclick=async()=>{try{await navigator.clipboard.writeText(value);copy.classList.add("copied");setTimeout(()=>copy.classList.remove("copied"),900)}catch{}};fields.append(row)})}
analyze.onclick=()=>{renderFields(lang==="sv-SE"?demoSv:demoEn);result.hidden=false;result.scrollIntoView({behavior:"smooth",block:"start"})};
addEventListener("pagehide",()=>items.forEach(item=>URL.revokeObjectURL(item.url)),{once:true});draw();
