(function(){
'use strict';
const RELEASE='V0.2.28', ANCHOR='2026-09-11';
const f=n=>Number(n||0).toLocaleString('sv-SE',{maximumFractionDigits:2});
const pct=n=>(100*Number(n||0)).toFixed(2)+'%';
function daysSinceAnchor(){const a=new Date(ANCHOR+'T00:00:00Z'),b=new Date();return Math.max(0,Math.floor((b-a)/86400000));}
function snap(){
 const e2=window.LinaG2ForwardEngine,e3=window.LinaG3ForwardEngine;
 const g2=e2.load()||e2.fresh(),g3=e3.load()||e3.fresh();
 return {schema:'LINA-FORWARD-EVIDENCE-CENTER-1',release:RELEASE,tradeEnabled:false,createdAt:new Date().toISOString(),anchor:ANCHOR,calendarDaysSinceAnchor:daysSinceAnchor(),g2:{candidate:e2.HASH,lastMarketDate:g2.lastMarketDate,lastRefreshAt:g2.lastRefreshAt,provider:g2.provider,stats:g2.stats||null,milestones:g2.milestones,closed:g2.closed?.length||0,open:g2.open?.length||0},g3:{planHash:e3.PLAN_HASH,lastMarketDate:g3.lastMarketDate,lastRefreshAt:g3.lastRefreshAt,provider:g3.provider,stats:g3.stats||null,milestones:g3.milestones,models:g3.models||[],closed:g3.closed?.length||0,open:g3.open?.length||0}};
}
function statusCard(label,x,detail){const s=x.stats||{};return `<div class="forward-center-card"><div><b>${label}</b><small>${detail}</small></div><div class="forward-summary"><div><small>Marknadsdag</small><b>${x.lastMarketDate||'—'}</b></div><div><small>Stängda</small><b>${x.closed||0}</b></div><div><small>Öppna</small><b>${x.open||0}</b></div><div><small>P/L</small><b>${s.pl==null?'—':(s.pl>=0?'+':'')+f(s.pl)}</b></div><div><small>PF</small><b>${s.pf==null?'—':Number.isFinite(s.pf)?f(s.pf):'∞'}</b></div><div><small>DD</small><b>${s.dd==null?'—':pct(s.dd)}</b></div></div></div>`}
function report(){const x=snap(),s2=x.g2.stats||{},s3=x.g3.stats||{},models=x.g3.models||[];return ['LINAS OPTI – FORWARD EVIDENCE CENTER',`Clean Core: ${RELEASE}`,'Handel: AVSTÄNGD',`Anchor: ${ANCHOR}`,`Kalenderdagar sedan anchor: ${x.calendarDaysSinceAnchor}`,'',`G2 · kandidat ${x.g2.candidate}`,`Senaste marknadsdag: ${x.g2.lastMarketDate||'—'} · stängda ${x.g2.closed} · öppna ${x.g2.open}`,`P/L ${f(s2.pl)} · PF ${s2.pf==null?'—':f(s2.pf)} · WR ${pct(s2.wr)} · DD ${pct(s2.dd)}`,'',`G3 · plan ${x.g3.planHash}`,`Senaste marknadsdag: ${x.g3.lastMarketDate||'—'} · stängda ${x.g3.closed} · öppna ${x.g3.open}`,`P/L ${f(s3.pl)} · PF ${s3.pf==null?'—':f(s3.pf)} · WR ${pct(s3.wr)} · DD ${pct(s3.dd)}`,`Aktuell månadsmodell: ${models.at(-1)?.month||'—'} ${models.at(-1)?.selectedHash||'—'}`,'','EVIDENSREGEL','Historiska G2–G12 ändras inte. Robotmognad 48/100. Forward-milstolpar 60/120/250 stängda affärer bedöms först när ny data faktiskt finns. Ingen automatisk mognadshöjning och ingen livehandel.'].join('\n')}
function dl(text,name,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function render(root,ctx){const x=snap();root.innerHTML=`<div class="crumb">Dashboard › Forward › Evidence Center</div><section class="hero"><h1>Forward Evidence Center</h1><p>Nu samlar Lina ny evidens i G2 och G3 parallellt. Historiska G2–G12 är frysta. Handel AV.</p></section><button class="back" id="fcBack">← Forward</button><section class="workspace"><div class="forward-lock"><b>🔒 FORSKNING FRYST</b><span>Anchor ${ANCHOR} · ${x.calendarDaysSinceAnchor} kalenderdagar sedan start · Robotmognad 48/100</span></div>${statusCard('G2 Real Forward',x.g2,'statisk kandidat '+x.g2.candidate)}${statusCard('G3 Real Forward',x.g3,'månadsvis lärande · plan '+x.g3.planHash)}<div id="fcStatus" class="statusline">${x.g2.lastRefreshAt||x.g3.lastRefreshAt?'Senaste sparade forward-status visas ovan.':'Forward är ännu inte uppdaterad i denna webbläsare.'}</div><div class="actions"><button id="fcRefresh" class="primary">↻ Uppdatera G2 + G3</button><button id="fcReport" class="secondary">📤 Exportera forward-bokslut</button><button id="fcRaw" class="secondary">Raw JSON</button></div><div class="forward-note"><b>Nästa evidensgrind:</b> 60 nya stängda affärer per forwardmodell är första formella milstolpen. 120 och 250 följer därefter. Tid i sig eller fler historiska tester höjer inte robotmognaden.</div></section>`;
 root.querySelector('#fcBack').onclick=ctx.back;
 root.querySelector('#fcReport').onclick=()=>dl(report(),`LINAS_OPTI_FORWARD_EVIDENCE_V0228_${new Date().toISOString().slice(0,10)}.txt`);
 root.querySelector('#fcRaw').onclick=()=>dl(JSON.stringify(snap(),null,2),`LINAS_OPTI_FORWARD_EVIDENCE_RAW_V0228_${new Date().toISOString().slice(0,10)}.json`,'application/json');
 root.querySelector('#fcRefresh').onclick=async()=>{const b=root.querySelector('#fcRefresh'),st=root.querySelector('#fcStatus');b.disabled=true;try{await window.LinaG2ForwardEngine.refresh(m=>st.textContent='G2 · '+m);await window.LinaG3ForwardEngine.refresh(m=>st.textContent='G3 · '+m);render(root,ctx)}catch(e){st.textContent='FEL: '+(e?.message||e);st.classList.add('bad');b.disabled=false}};
}
window.LinaForwardCenter={render,report,snap};
})();
