(function(){
'use strict';
const RELEASE='V0.2.43', ANCHOR='2026-09-11', API='https://linas-opti-api.mangaj73.workers.dev';
const HISTORY={g2:{documented:true,status:'AKTIV · HISTORIK FINNS',anchor:ANCHOR,candidate:'15efd75a',note:'G2 Real Forward är dokumenterat som startat/aktivt i projekthistoriken.'},g3:{documented:true,status:'AKTIV · HISTORIK FINNS',anchor:ANCHOR,planHash:'75838ed5',note:'G3 Real Forward är dokumenterat som startat/aktivt i projekthistoriken.'}};
const f=n=>Number(n||0).toLocaleString('sv-SE',{maximumFractionDigits:2});
const pct=n=>(100*Number(n||0)).toFixed(2)+'%';
function daysSinceAnchor(){const a=new Date(ANCHOR+'T00:00:00Z'),b=new Date();return Math.max(0,Math.floor((b-a)/86400000));}
function engines(){return {g2:window.LinaG2ForwardEngine,g3:window.LinaG3ForwardEngine}}
function snap(){const {g2:e2,g3:e3}=engines(),g2=e2.normalizeState(e2.load()||e2.fresh()),g3=e3.normalizeState(e3.load()||e3.fresh());return {schema:'LINA-FORWARD-EVIDENCE-CENTER-2',release:RELEASE,tradeEnabled:false,createdAt:new Date().toISOString(),anchor:ANCHOR,calendarDaysSinceAnchor:daysSinceAnchor(),sync:{format:'LINA-FORWARD-SYNC-1',mode:'GitHub master via Cloudflare Worker',note:'Permanent history is facit; GitHub is shared master for compact Forward runtime.'},g2:{history:HISTORY.g2,localState:!!g2.lastRefreshAt,candidate:e2.HASH,lastMarketDate:g2.lastMarketDate,lastRefreshAt:g2.lastRefreshAt,provider:g2.provider,stats:g2.stats||null,milestones:g2.milestones,closed:g2.closed?.length||0,open:g2.open?.length||0},g3:{history:HISTORY.g3,localState:!!g3.lastRefreshAt,planHash:e3.PLAN_HASH,lastMarketDate:g3.lastMarketDate,lastRefreshAt:g3.lastRefreshAt,provider:g3.provider,stats:g3.stats||null,milestones:g3.milestones,models:g3.models||[],closed:g3.closed?.length||0,open:g3.open?.length||0}}}
function statusCard(label,x,detail){const s=x.stats||{},local=x.localState;return `<div class="forward-center-card"><div><b>${label}</b><small>${detail}</small><small><b>${x.history?.status||''}</b> · ${local?'lokal runtime-data finns på denna enhet':'ingen lokal runtime-data på denna enhet'}</small></div><div class="forward-summary"><div><small>Marknadsdag</small><b>${x.lastMarketDate||'—'}</b></div><div><small>Stängda</small><b>${x.closed||0}</b></div><div><small>Öppna</small><b>${x.open||0}</b></div><div><small>P/L</small><b>${s.pl==null?'—':(s.pl>=0?'+':'')+f(s.pl)}</b></div><div><small>PF</small><b>${s.pf==null?'—':Number.isFinite(s.pf)?f(s.pf):'∞'}</b></div><div><small>DD</small><b>${s.dd==null?'—':pct(s.dd)}</b></div></div></div>`}
function report(){const x=snap(),s2=x.g2.stats||{},s3=x.g3.stats||{},models=x.g3.models||[];return ['LINAS OPTI – FORWARD EVIDENCE CENTER',`Clean Core: ${RELEASE}`,'Handel: AVSTÄNGD',`Anchor: ${ANCHOR}`,`Kalenderdagar sedan anchor: ${x.calendarDaysSinceAnchor}`,'',`G2 · kandidat ${x.g2.candidate}`,`Senaste marknadsdag: ${x.g2.lastMarketDate||'—'} · stängda ${x.g2.closed} · öppna ${x.g2.open}`,`P/L ${f(s2.pl)} · PF ${s2.pf==null?'—':f(s2.pf)} · WR ${pct(s2.wr)} · DD ${pct(s2.dd)}`,'',`G3 · plan ${x.g3.planHash}`,`Senaste marknadsdag: ${x.g3.lastMarketDate||'—'} · stängda ${x.g3.closed} · öppna ${x.g3.open}`,`P/L ${f(s3.pl)} · PF ${s3.pf==null?'—':f(s3.pf)} · WR ${pct(s3.wr)} · DD ${pct(s3.dd)}`,`Aktuell månadsmodell: ${models.at(-1)?.month||'—'} ${models.at(-1)?.selectedHash||'—'}`,'','SYNCREGEL','Varje forward-affär har deterministiskt ID. Import merge:ar runtime-state och stoppar vid konflikt; permanent projekthistorik skrivs aldrig över.','','EVIDENSREGEL','Historiska G2–G12 ändras inte. Robotmognad 48/100. Forward-milstolpar 60/120/250 bedöms först när ny data faktiskt finns. Ingen automatisk mognadshöjning och ingen livehandel.'].join('\n')}
function dl(text,name,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function statePackage(){const {g2,g3}=engines(),completedThrough=g2.safeCompletedDate?.()||g3.safeCompletedDate?.()||null;return {schema:'LINA-FORWARD-SYNC-1',release:RELEASE,exportedAt:new Date().toISOString(),anchor:ANCHOR,tradeEnabled:false,completedThrough,g2:g2.normalizeState(g2.load()||g2.fresh()),g3:g3.normalizeState(g3.load()||g3.fresh())}}
function canon(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(canon).join(',')+']';return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canon(v[k])).join(',')+'}'}
function mergeArray(local,incoming,idFn,label){const map=new Map();for(const t of local||[])map.set(t.tradeId||idFn(t),t);for(const raw of incoming||[]){const t={...raw,tradeId:raw.tradeId||idFn(raw)},old=map.get(t.tradeId);if(old&&canon(old)!==canon(t))throw new Error(`${label}: konflikt för ${t.tradeId}`);map.set(t.tradeId,t)}return [...map.values()]}
function mergeHistory(a,b){const key=x=>[x.at,x.event,x.marketDate,x.closed,x.model].join('|'),m=new Map();for(const x of [...(a||[]),...(b||[])])m.set(key(x),x);return [...m.values()].sort((x,y)=>String(x.at||'').localeCompare(String(y.at||''))).slice(-80)}
function later(a,b){return String(a||'')>=String(b||'')?a:b}
function mergeState(local,incoming,e,kind){
 local=e.normalizeState(local||e.fresh());incoming=e.normalizeState(incoming||e.fresh());
 if(incoming.anchor!==ANCHOR)throw new Error(`${kind}: fel anchor ${incoming.anchor||'saknas'}`);
 if(kind==='G2'&&incoming.candidateHash!==e.HASH)throw new Error(`G2: kandidatkonflikt ${incoming.candidateHash}`);
 if(kind==='G3'&&incoming.planHash!==e.PLAN_HASH)throw new Error(`G3: plankonflikt ${incoming.planHash}`);
 let models=local.models;
 if(kind==='G3'){const mm=new Map((local.models||[]).map(x=>[x.month,x]));for(const x of incoming.models||[]){const old=mm.get(x.month);if(old&&canon(old)!==canon(x))throw new Error(`G3: modellkonflikt ${x.month}`);mm.set(x.month,x)}models=[...mm.values()].sort((a,b)=>a.month.localeCompare(b.month))}
 const ld=String(local.lastMarketDate||''),id=String(incoming.lastMarketDate||'');
 let base;
 if(id>ld) base={...incoming}; else if(ld>id) base={...local}; else {
   const closed=mergeArray(local.closed,incoming.closed,t=>e.tradeId(t,'CLOSED'),kind+' stängd');
   const open=mergeArray(local.open,incoming.open,t=>e.tradeId(t,'OPEN'),kind+' öppen');
   if(closed.length!==Math.max(local.closed?.length||0,incoming.closed?.length||0)||open.length!==Math.max(local.open?.length||0,incoming.open?.length||0))throw new Error(`${kind}: olika snapshots för samma marknadsdag ${ld||'—'}`);
   base={...(String(incoming.lastRefreshAt||'')>String(local.lastRefreshAt||'')?incoming:local),closed,open};
 }
 base.history=mergeHistory(local.history,incoming.history);base.lastMarketDate=later(local.lastMarketDate,incoming.lastMarketDate);base.lastRefreshAt=later(local.lastRefreshAt,incoming.lastRefreshAt);
 base.milestones={60:(base.closed?.length||0)>=60||local.milestones?.[60]||incoming.milestones?.[60],120:(base.closed?.length||0)>=120||local.milestones?.[120]||incoming.milestones?.[120],250:(base.closed?.length||0)>=250||local.milestones?.[250]||incoming.milestones?.[250]};
 if(kind==='G3')base.models=models;return e.normalizeState(base)
}
async function importPackage(file){const txt=await file.text();let p;try{p=JSON.parse(txt)}catch{throw new Error('Filen är inte giltig JSON')};if(p.schema!=='LINA-FORWARD-SYNC-1')throw new Error('Fel filtyp – välj en Forward-state backup från V0.2.30+');if(p.anchor!==ANCHOR)throw new Error('Anchor-konflikt – import avbruten');const {g2,g3}=engines(),m2=mergeState(g2.load(),p.g2,g2,'G2'),m3=mergeState(g3.load(),p.g3,g3,'G3');g2.save(m2);g3.save(m3);return {g2:m2,g3:m3}}
function loginCode(){return sessionStorage.getItem('linasopti_login_code')||''}
async function remoteGet(){const r=await fetch(API+'/forward-state',{cache:'no-store'}),j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.error||('HTTP '+r.status));return j}
async function remotePush(){const code=loginCode();if(!code)throw new Error('Lina-session saknas – logga in igen');const p=statePackage(),r=await fetch(API+'/forward-state',{method:'POST',headers:{'Content-Type':'application/json','X-Lina-Login-Code':code},body:JSON.stringify(p)}),j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.error||('HTTP '+r.status));const {g2,g3}=engines();if(j.state?.g2)g2.save(g2.normalizeState(j.state.g2));if(j.state?.g3)g3.save(g3.normalizeState(j.state.g3));return j}
async function remotePull(){const j=await remoteGet();if(!j.exists||!j.state)return {exists:false};const {g2,g3}=engines();const m2=mergeState(g2.load(),j.state.g2,g2,'G2'),m3=mergeState(g3.load(),j.state.g3,g3,'G3');g2.save(m2);g3.save(m3);return {exists:true,g2:m2,g3:m3,path:j.path,branch:j.branch}}
let autoPromise=null;
async function autoCatchUp(progress){
 if(autoPromise)return autoPromise;
 autoPromise=(async()=>{
  const {g2,g3}=engines(),cutoff=g2.safeCompletedDate?.()||g3.safeCompletedDate?.();
  progress?.('Läser gemensam Forward-master…');
  const r=await remotePull();
  const s2=g2.normalizeState(g2.load()||g2.fresh()),s3=g3.normalizeState(g3.load()||g3.fresh());
  const latest=later(s2.lastMarketDate,s3.lastMarketDate)||'';
  if(!cutoff||latest===cutoff){progress?.(`Forward är aktuell t.o.m. ${latest||'—'}`);return {updated:false,cutoff,latest};}
  progress?.(latest>cutoff?`Reparerar ofullständig marknadsdag ${latest} → säker cutoff ${cutoff}…`:`Nya avslutade marknadsdagar finns · uppdaterar t.o.m. ${cutoff}…`);
  await g2.refresh(m=>progress?.('G2 · '+m));
  await g3.refresh(m=>progress?.('G3 · '+m));
  progress?.('Sparar gemensam Forward-master…');
  await remotePush();
  const a=g2.load(),b=g3.load(),done=later(a?.lastMarketDate,b?.lastMarketDate)||'—';
  progress?.(`Forward automatiskt uppdaterad · t.o.m. ${done}`);
  return {updated:true,cutoff,latest:done};
 })().finally(()=>setTimeout(()=>{autoPromise=null},1500));
 return autoPromise;
}
function render(root,ctx){const x=snap();root.innerHTML=`<div class="crumb">Dashboard › Forward › Evidence Center</div><section class="hero"><h1>Forward Evidence Center</h1><p>Ny evidens i G2 och G3 parallellt. Historiska G2–G12 är frysta. Handel AV.</p></section><button class="back" id="fcBack">← Forward</button><section class="workspace"><div class="forward-lock"><b>🔒 FORSKNING FRYST</b><span>Anchor ${ANCHOR} · ${x.calendarDaysSinceAnchor} kalenderdagar sedan start · Robotmognad 48/100</span></div>${statusCard('G2 Real Forward',x.g2,'statisk kandidat '+x.g2.candidate)}${statusCard('G3 Real Forward',x.g3,'månadsvis lärande · plan '+x.g3.planHash)}<div id="fcStatus" class="statusline">${x.g2.lastRefreshAt||x.g3.lastRefreshAt?'Lokal runtime-status visas ovan. Permanent historik är separat och bevarad.':'Permanent forward-historik finns. Den här enheten saknar bara lokal runtime-data.'}</div><div class="actions"><button id="fcRefresh" class="primary">↻ Uppdatera G2 + G3</button><button id="fcSync" class="secondary">☁ Synka GitHub</button><button id="fcBackup" class="secondary">💾 Lokal backup</button><button id="fcImport" class="secondary">↥ Importera backup</button><input id="fcFile" type="file" accept="application/json,.json" hidden><button id="fcReport" class="secondary">📤 Forward-bokslut</button><button id="fcRaw" class="secondary">Raw JSON</button></div><div class="forward-note"><b>Gemensam master:</b> Forward-state läses från och sparas till GitHub via Cloudflare Worker. Lokal backup/import finns kvar som nödfunktion. Synk stoppar hellre än att skriva över en konflikt.</div><div class="forward-note"><b>Nästa evidensgrind:</b> 60 nya stängda affärer per forwardmodell. 120 och 250 följer därefter. Tid eller fler historiska tester höjer inte robotmognaden.</div></section>`;
 root.querySelector('#fcBack').onclick=ctx.back;root.querySelector('#fcReport').onclick=()=>dl(report(),`LINAS_OPTI_FORWARD_EVIDENCE_V0232_${new Date().toISOString().slice(0,10)}.txt`);root.querySelector('#fcRaw').onclick=()=>dl(JSON.stringify(snap(),null,2),`LINAS_OPTI_FORWARD_EVIDENCE_RAW_V0232_${new Date().toISOString().slice(0,10)}.json`,'application/json');root.querySelector('#fcBackup').onclick=()=>dl(JSON.stringify(statePackage(),null,2),`LINAS_OPTI_FORWARD_STATE_BACKUP_V0232_${new Date().toISOString().slice(0,10)}.json`,'application/json');
 const inp=root.querySelector('#fcFile'),st=root.querySelector('#fcStatus');root.querySelector('#fcSync').onclick=async()=>{st.textContent='Synkar med GitHub…';try{const r=await remotePull();if(!r.exists){st.textContent='Ingen GitHub-master ännu – skapar från denna enhet…';await remotePush()}else await remotePush();st.textContent='GitHub-synk klar';setTimeout(()=>render(root,ctx),700)}catch(e){st.textContent='GITHUB-SYNK STOPPAD: '+(e?.message||e);st.classList.add('bad')}};root.querySelector('#fcImport').onclick=()=>inp.click();inp.onchange=async()=>{if(!inp.files?.[0])return;st.textContent='Kontrollerar och merge:ar Forward-state…';try{const r=await importPackage(inp.files[0]);st.textContent=`Synk klar · G2 ${r.g2.closed.length} stängda · G3 ${r.g3.closed.length} stängda · t.o.m. ${later(r.g2.lastMarketDate,r.g3.lastMarketDate)||'—'}`;setTimeout(()=>render(root,ctx),700)}catch(e){st.textContent='SYNK STOPPAD: '+(e?.message||e);st.classList.add('bad')}finally{inp.value=''}};
 root.querySelector('#fcRefresh').onclick=async()=>{const b=root.querySelector('#fcRefresh');b.disabled=true;try{await window.LinaG2ForwardEngine.refresh(m=>st.textContent='G2 · '+m);await window.LinaG3ForwardEngine.refresh(m=>st.textContent='G3 · '+m);st.textContent='Sparar gemensamt Forward-state till GitHub…';await remotePush();render(root,ctx)}catch(e){st.textContent='FEL: '+(e?.message||e);st.classList.add('bad');b.disabled=false}};
 setTimeout(async()=>{try{await autoCatchUp(m=>st.textContent=m);setTimeout(()=>render(root,ctx),700)}catch(e){st.textContent='AUTO-FORWARD STOPPAD: '+(e?.message||e);st.classList.add('bad')}},0);
}
window.LinaForwardCenter={render,report,snap,statePackage,importPackage,mergeState,remoteGet,remotePull,remotePush,autoCatchUp};
})();
