(function(){
'use strict';
const VERSION='V0.2.14';
const PLAN_KEY='lina_clean_swing_g4_universe_plan_v0212';
const RESULT_KEY='lina_clean_swing_g4_universe_result_v0214';
const LEGACY_KEY='lina_clean_swing_g4_universe_result_v0213';
const DB_NAME='lina_g4_marketdata_v0214', STORE='chunks';
const PLAN_HASH='95d2e735', CANDIDATE='15efd75a';
const START='2020-01-01',END='2026-09-10';
const TEST=['AAPL','MSFT','AMZN','GOOGL','META','JPM','XOM','UNH','JNJ','PG','KO','CAT','HD','DIS','NKE','WMT'];
const PARAMS={breakout:55,trend:'sma200',volume:1.5,regime:'spy200',stop:.07,target:.15,hold:10};
const API='https://linas-opti-api.mangaj73.workers.dev';
function loadPlan(){try{return JSON.parse(localStorage.getItem(PLAN_KEY)||'null')}catch{return null}}
function load(){try{return JSON.parse(localStorage.getItem(RESULT_KEY)||'null')}catch{return null}}
function compact(x){const y={...x};if(y.fetch)y.fetch={year:y.fetch.year||0,symbol:y.fetch.symbol||0};delete y._rows;return y}
function save(x){x.savedAt=new Date().toISOString();const s=JSON.stringify(compact(x));if(s.length>350000)throw new Error('G4 compact state safety limit exceeded ('+s.length+' bytes).');try{localStorage.setItem(RESULT_KEY,s)}catch(e){throw new Error('G4 compact state could not be saved safely: '+(e.message||e))}document.dispatchEvent(new CustomEvent('lina:g4change'));return x}
function emit(stage,detail=''){document.dispatchEvent(new CustomEvent('lina:g4live',{detail:{stage,detail}}))}
function fresh(){return{schema:'LINA-SWING-G4-UNIVERSE-RESULT-2',version:VERSION,planHash:PLAN_HASH,candidate:CANDIDATE,period:[START,END],testUniverse:TEST,params:PARAMS,tradeEnabled:false,status:'ready',fetch:{year:0,symbol:0},result:null,gate:null,ledger:[],storage:{marketData:'IndexedDB',rawInLocalStorage:false}}}
function db(){return new Promise((res,rej)=>{const q=indexedDB.open(DB_NAME,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function putChunk(id,rows){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(rows,id);tx.oncomplete=()=>{d.close();res()};tx.onerror=()=>{d.close();rej(tx.error)}})}
async function allRows(){const d=await db();return new Promise((res,rej)=>{const q=d.transaction(STORE,'readonly').objectStore(STORE).getAll();q.onsuccess=()=>{d.close();res(q.result.flat())};q.onerror=()=>{d.close();rej(q.error)}})}
async function clearRows(){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();tx.oncomplete=()=>{d.close();res()};tx.onerror=()=>{d.close();rej(tx.error)}})}
async function migrateLegacy(){if(load())return;let old=null;try{old=JSON.parse(localStorage.getItem(LEGACY_KEY)||'null')}catch{}if(!old)return;if(old.fetch?.rows?.length){emit('ÅTERSTÄLLER CHECKPOINT','Flyttar V0.2.13 rådata från localStorage till IndexedDB');await clearRows();await putChunk('legacy-checkpoint',old.fetch.rows);const x={...old,version:VERSION,schema:'LINA-SWING-G4-UNIVERSE-RESULT-2',fetch:{year:old.fetch.year||0,symbol:old.fetch.symbol||0},storage:{marketData:'IndexedDB',rawInLocalStorage:false,migratedFrom:'V0.2.13'}};delete x.result;delete x.gate;save(x);localStorage.removeItem(LEGACY_KEY);return x}localStorage.removeItem(LEGACY_KEY)}
function years(){const a=[];for(let y=2020;y<=2026;y++)a.push([`${y}-01-01`,y===2026?END:`${y}-12-31`]);return a}
async function bridge(path){const r=await fetch(API+path,{cache:'no-store'});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||('HTTP '+r.status));return j}
function rowsOf(j){return Array.isArray(j)?j:(j?.rows||j?.data||[])}
async function fetchSymbol(sym,a,b){const tries=[['Worker Yahoo daily',`/yahoo-bars?symbols=${encodeURIComponent(sym)}&timeframe=1Day&start=${a}&end=${b}`],['EODHD .US',`/eod-bars?symbols=${encodeURIComponent(sym+'.US')}&timeframe=1Day&start=${a}&end=${b}`],['Alpaca daily',`/bars?symbols=${encodeURIComponent(sym)}&timeframe=1Day&start=${a}T00:00:00Z&end=${b}T23:59:59Z`]];let errs=[];for(let cycle=1;cycle<=2;cycle++){for(const [name,path] of tries){try{emit('HÄMTAR G4',`${sym} · ${a} → ${b} · ${name} · försök ${cycle}/2`);const j=await Promise.race([bridge(path),new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout 60 s')),60000))]);let rows=rowsOf(j);if(!rows.length)throw new Error('0 dagsrader');return rows.map(r=>({...r,symbol:sym,s:sym,provider:name}))}catch(e){errs.push(`${name}: ${e.message||e}`)}}}throw new Error(`${sym} ${a}–${b}: ${errs.slice(-3).join(' | ')}`)}
function stats(trades){const gp=trades.filter(t=>t.pnl>0).reduce((s,t)=>s+t.pnl,0),gl=-trades.filter(t=>t.pnl<0).reduce((s,t)=>s+t.pnl,0),pl=trades.reduce((s,t)=>s+t.pnl,0),n=trades.length,w=trades.filter(t=>t.pnl>0).length;return{n,pl,pf:gl?gp/gl:(gp?Infinity:0),wr:n?w/n:0}}
function evaluate(r){const closed=r.closed||[],ys={};for(const t of closed){const y=String(t.exitDate).slice(0,4);(ys[y]??=[]).push(t)}const yearRows=Object.entries(ys).sort().map(([year,a])=>({year,...stats(a)}));const positiveCalendarSegments=yearRows.filter(y=>y.pl>0).length;const sy={};for(const t of closed)(sy[t.symbol]??=[]).push(t);const symbolRows=Object.entries(sy).map(([symbol,a])=>({symbol,...stats(a)})).sort((a,b)=>b.pl-a.pl);const positivePL=symbolRows.filter(s=>s.pl>0).reduce((z,s)=>z+s.pl,0),maxPositive=symbolRows.filter(s=>s.pl>0).sort((a,b)=>b.pl-a.pl)[0]||null,maxShare=positivePL&&maxPositive?maxPositive.pl/positivePL:0;const pass=r.n>=100&&r.pl>0&&r.pf>=1.15&&r.dd>=-.08&&positiveCalendarSegments>=4&&maxShare<=.5;const hold=r.n>=60&&r.pl>0&&r.pf>=1&&r.dd>=-.12;return{verdict:pass?'PASS':hold?'HOLD':'FAIL',positiveCalendarSegments,maxSingleSymbolSharePositivePL:maxShare,maxPositiveSymbol:maxPositive?.symbol||null,years:yearRows,symbols:symbolRows,criteria:{pass:{minTrades:100,plPositive:true,minPF:1.15,maxDDAbs:.08,minPositiveCalendarSegments:4,maxSingleSymbolSharePositivePL:.5},hold:{minTrades:60,plPositive:true,minPF:1,maxDDAbs:.12}}}}
async function run(){const p=loadPlan();if(!p?.locked||p.planHash!==PLAN_HASH)throw new Error('G4-planen måste vara låst med planhash '+PLAN_HASH+' före körning.');await migrateLegacy();let x=load()||fresh();if(x.status==='complete')return x;if(!load()){await clearRows();save(x)}x.status='running';x.startedAt=x.startedAt||new Date().toISOString();x.ledger??=[];if(!x.ledger.some(e=>e.event==='RESULT_OPEN'))x.ledger.push({at:new Date().toISOString(),event:'RESULT_OPEN',planHash:PLAN_HASH,candidate:CANDIDATE});save(x);try{const yy=years(),symbols=[...TEST,'SPY'];x.fetch??={year:0,symbol:0};while(x.fetch.year<yy.length){const[a,b]=yy[x.fetch.year];while(x.fetch.symbol<symbols.length){const sym=symbols[x.fetch.symbol];emit('G4 UNIVERSE ROBUSTNESS',`År ${x.fetch.year+1}/${yy.length} · symbol ${x.fetch.symbol+1}/${symbols.length} · ${sym}`);const rows=await fetchSymbol(sym,a,b);await putChunk(`${x.fetch.year}-${x.fetch.symbol}-${sym}`,rows);x.fetch.symbol++;save(x);await new Promise(r=>setTimeout(r,20))}x.fetch.year++;x.fetch.symbol=0;save(x)}emit('BERÄKNAR G4','Läser rådata från IndexedDB · exakt fryst G2 15efd75a');const E=window.LinaG2Engine;if(!E?.engine||!E?.normRows)throw new Error('G2-motorn saknas.');const raw=await allRows(),rows=E.normRows(raw),r=E.engine(rows,PARAMS,.001,TEST),gate=evaluate(r);x.result={start:START,end:END,n:r.n,pl:r.pl,pf:r.pf,wr:r.wr,dd:r.dd,avg:r.avg,final:r.final,capitalUse:r.capitalUse,blocked:r.blocked,closed:r.closed};x.gate=gate;x.status='complete';x.finishedAt=new Date().toISOString();x.providers=[...new Set(rows.map(z=>z.provider).filter(Boolean))];x.dataRows=rows.length;x.ledger.push({at:x.finishedAt,event:'GATE',verdict:gate.verdict,n:r.n,pl:r.pl,pf:r.pf,dd:r.dd,noRescue:true});delete x.fetch;save(x);await clearRows();emit('G4 KLART',`${gate.verdict} · ${r.n} affärer · PF ${r.pf.toFixed(2)}`);return x}catch(e){x=load()||x;x.status='error';x.lastError={at:new Date().toISOString(),message:e.message||String(e)};x.ledger??=[];x.ledger.push({at:x.lastError.at,event:'RUN_ERROR',message:x.lastError.message});try{save(x)}catch{}emit('G4 KÖRFEL',x.lastError.message);throw e}}
function report(){const x=load();if(!x?.result)return'G4-resultat saknas.';const r=x.result,g=x.gate,f=n=>Number(n).toLocaleString('sv-SE',{maximumFractionDigits:2}),pct=n=>(100*n).toFixed(2)+'%';let L=['LINAS OPTI – G4 UNIVERSE ROBUSTNESS','Clean Core: '+VERSION,'Handel: AVSTÄNGD','Plan: '+PLAN_HASH+' · kandidat '+CANDIDATE,'Period: '+START+' → '+END,'','RESULTAT',`${r.n} affärer · P/L ${f(r.pl)} · PF ${f(r.pf)} · WR ${pct(r.wr)} · DD ${pct(r.dd)} · slut ${f(r.final)}`,'','GATE: '+g.verdict,`Positiva kalendersegment: ${g.positiveCalendarSegments}`,`Största positiva symbolandel: ${pct(g.maxSingleSymbolSharePositivePL)} (${g.maxPositiveSymbol||'—'})`,'','ÅR'];g.years.forEach(y=>L.push(`${y.year} · ${y.n} affärer · P/L ${f(y.pl)} · PF ${f(y.pf)} · WR ${pct(y.wr)}`));L.push('','SYMBOLER');g.symbols.forEach(s=>L.push(`${s.symbol} · ${s.n} affärer · P/L ${f(s.pl)} · PF ${Number.isFinite(s.pf)?f(s.pf):'∞'} · WR ${pct(s.wr)}`));L.push('','EVIDENSBEGRÄNSNING','G4 är robusthets-/portabilitetstest, inte ny oberoende OOS. Ingen rescue eller parameterändring tillåts efter resultat. G2/G3 Real Forward har högre evidens.');return L.join('\n')}
function dl(text,name,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportReport(){dl(report(),`LINAS_OPTI_G4_UNIVERSE_V0214_${new Date().toISOString().slice(0,10)}.txt`)}
function exportRaw(){const x=load();if(x)dl(JSON.stringify(x,null,2),`LINAS_OPTI_G4_UNIVERSE_RAW_V0214_${new Date().toISOString().slice(0,10)}.json`,'application/json')}
window.LinaG4Engine={VERSION,PLAN_HASH,CANDIDATE,TEST,PARAMS,load,run,report,exportReport,exportRaw,evaluate};
})();
