(function(){
'use strict';
const VERSION='0.2.12',KEY='lina_clean_swing_g4_universe_plan_v0212',PLAN_HASH='95d2e735';
const TEST=['AAPL','MSFT','AMZN','GOOGL','META','JPM','XOM','UNH','JNJ','PG','KO','CAT','HD','DIS','NKE','WMT'];
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
function lock(){let x=load();if(x?.locked)return x;x={schema:'LINA-G4-UNIVERSE-PLAN-1',version:'V0.2.12',locked:true,planHash:PLAN_HASH,lockedAt:new Date().toISOString(),candidate:'15efd75a',period:['2020-01-01','2026-09-10'],testUniverse:TEST,tradeEnabled:false,resultOpened:false};localStorage.setItem(KEY,JSON.stringify(x));return x}
function render(root,ctx){const x=load();root.innerHTML=`<div class="crumb">Dashboard › Forskning › Swing G4 Universe Robustness</div><section class="hero"><h1>G4 Universe Robustness</h1><p>Testar om fryst G2 fungerar på andra aktier. Ingen parameterjakt. Handel AV.</p></section><button class="back" id="g4Back">← Forskning</button><section class="workspace"><div class="forward-lock"><b>${x?.locked?'🔒 G4 PLAN LÅST':'G4 PLAN FÖRREGISTRERAD'}</b><span>Plan ${PLAN_HASH} · kandidat 15efd75a · resultat ännu ej öppnat</span></div><h2>Fryst testuniversum</h2><p>${TEST.join(' · ')}</p><div class="statusline"><b>Period:</b> 2020-01-01 → 2026-09-10 · exakt G2-strategi · SPY används endast som regimfilter.</div><h2>Gate före resultat</h2><p><b>PASS:</b> ≥100 affärer, P/L &gt; 0, PF ≥1,15, DD ≥−8 %, minst 4 positiva kalendersegment och inget bolag &gt;50 % av positiv P/L.</p><p><b>HOLD:</b> ≥60 affärer, P/L &gt; 0, PF ≥1,00 och DD ≥−12 %. Annars FAIL.</p><div class="forward-note"><b>Begränsning:</b> G4 är robusthets-/portabilitetstest, inte ny oberoende OOS. Universumet är definierat 2026 och är inte ett historiskt point-in-time-index. G2/G3 Real Forward har högre evidens.</div><div class="actions">${x?.locked?'<button class="secondary" disabled>✓ Plan låst · nästa release kör G4</button>':'<button id="g4Lock" class="primary">🔒 Lås G4-planen</button>'}</div></section>`;root.querySelector('#g4Back').onclick=ctx.back;const b=root.querySelector('#g4Lock');if(b)b.onclick=()=>{lock();render(root,ctx)}}
window.LinaG4={render,lock,load,PLAN_HASH};
})();
