(function(){
'use strict';
const VERSION='V0.2.17';
const PLAN_KEY='lina_clean_swing_g5_stress_plan_v0216';
const RESULT_KEY='lina_clean_swing_g5_stress_result_v0217';
const DB_NAME='lina_g5_marketdata_v0217',STORE='chunks';
const PLAN_HASH='6ec36eb2',CANDIDATE='15efd75a';
const START='2020-01-01',END='2026-09-10';
const TEST=['AAPL','MSFT','AMZN','GOOGL','META','JPM','XOM','UNH','JNJ','PG','KO','CAT','HD','DIS','NKE','WMT'];
const PARAMS={breakout:55,trend:'sma200',volume:1.5,regime:'spy200',stop:.07,target:.15,hold:10};
const BASE_COST=.001,CAPITAL=100000,RISK=.005,MAXPOS=5,MAXPOSPCT=.20;
const API='https://linas-opti-api.mangaj73.workers.dev';
const SCENARIOS=[
{id:'COST_10',label:'Extra kostnad 0,10 % per sida',extraCostPerSide:.001,entryDelayTradingDays:0},
{id:'COST_25',label:'Extra kostnad 0,25 % per sida',extraCostPerSide:.0025,entryDelayTradingDays:0},
{id:'COST_50',label:'Extra kostnad 0,50 % per sida',extraCostPerSide:.005,entryDelayTradingDays:0},
{id:'DELAY_1',label:'Entry fördröjd 1 handelsdag',extraCostPerSide:0,entryDelayTradingDays:1},
{id:'COMBINED',label:'0,25 % extra per sida + 1 handelsdags entryfördröjning',extraCostPerSide:.0025,entryDelayTradingDays:1}
];
function plan(){try{return JSON.parse(localStorage.getItem(PLAN_KEY)||'null')}catch{return null}}
function load(){try{return JSON.parse(localStorage.getItem(RESULT_KEY)||'null')}catch{return null}}
function save(x){x.savedAt=new Date().toISOString();const s=JSON.stringify(x);if(s.length>350000)throw new Error('G5 compact state safety limit exceeded ('+s.length+' bytes).');try{localStorage.setItem(RESULT_KEY,s)}catch(e){throw new Error('G5 compact state could not be saved safely: '+(e.message||e))}document.dispatchEvent(new CustomEvent('lina:g5change'));return x}
function emit(stage,detail=''){document.dispatchEvent(new CustomEvent('lina:g5live',{detail:{stage,detail}}))}
function fresh(){return{schema:'LINA-SWING-G5-STRESS-RESULT-1',version:VERSION,planHash:PLAN_HASH,candidate:CANDIDATE,period:[START,END],universe:TEST,params:PARAMS,baseCostPerSide:BASE_COST,tradeEnabled:false,status:'ready',fetch:{year:0,symbol:0},scenarios:null,gate:null,ledger:[],storage:{marketData:'IndexedDB',rawInLocalStorage:false}}}
function db(){return new Promise((res,rej)=>{const q=indexedDB.open(DB_NAME,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function putChunk(id,rows){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(rows,id);tx.oncomplete=()=>{d.close();res()};tx.onerror=()=>{d.close();rej(tx.error)}})}
async function allRows(){const d=await db();return new Promise((res,rej)=>{const q=d.transaction(STORE,'readonly').objectStore(STORE).getAll();q.onsuccess=()=>{d.close();res(q.result.flat())};q.onerror=()=>{d.close();rej(q.error)}})}
async function clearRows(){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();tx.oncomplete=()=>{d.close();res()};tx.onerror=()=>{d.close();rej(tx.error)}})}
function years(){const a=[];for(let y=2020;y<=2026;y++)a.push([`${y}-01-01`,y===2026?END:`${y}-12-31`]);return a}
async function bridge(path){const r=await fetch(API+path,{cache:'no-store'});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||('HTTP '+r.status));return j}
function rowsOf(j){return Array.isArray(j)?j:(j?.rows||j?.data||[])}
async function fetchSymbol(sym,a,b){const tries=[['Worker Yahoo daily',`/yahoo-bars?symbols=${encodeURIComponent(sym)}&timeframe=1Day&start=${a}&end=${b}`],['EODHD .US',`/eod-bars?symbols=${encodeURIComponent(sym+'.US')}&timeframe=1Day&start=${a}&end=${b}`],['Alpaca daily',`/bars?symbols=${encodeURIComponent(sym)}&timeframe=1Day&start=${a}T00:00:00Z&end=${b}T23:59:59Z`]];let errs=[];for(let cycle=1;cycle<=2;cycle++)for(const[name,path]of tries){try{emit('HÄMTAR G5',`${sym} · ${a} → ${b} · ${name} · försök ${cycle}/2`);const j=await Promise.race([bridge(path),new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout 60 s')),60000))]);const rows=rowsOf(j);if(!rows.length)throw new Error('0 dagsrader');return rows.map(r=>({...r,symbol:sym,s:sym,provider:name}))}catch(e){errs.push(`${name}: ${e.message||e}`)}}throw new Error(`${sym} ${a}–${b}: ${errs.slice(-3).join(' | ')}`)}
function dateOf(r){return String(r.t).slice(0,10)}
function prep(rows){const by={};for(const r of rows)(by[r.symbol]??=[]).push(r);for(const a of Object.values(by))a.sort((x,y)=>x.t.localeCompare(y.t));return by}
function sma(a,i,n){if(i-n+1<0)return null;let s=0;for(let k=i-n+1;k<=i;k++)s+=a[k].c;return s/n}
function avgVol(a,i,n=20){if(i-n+1<0)return null;let s=0;for(let k=i-n+1;k<=i;k++)s+=(+a[k].v||0);return s/n}
function prevCloseHigh(a,i,n){if(i-n<0)return null;let h=-Infinity;for(let k=i-n;k<=i-1;k++)h=Math.max(h,a[k].c);return h}
function tradeStats(closed){const n=closed.length,w=closed.filter(x=>x.pnl>0),l=closed.filter(x=>x.pnl<0),gw=w.reduce((s,x)=>s+x.pnl,0),gl=-l.reduce((s,x)=>s+x.pnl,0),pl=closed.reduce((s,x)=>s+x.pnl,0);let eq=CAPITAL,peak=CAPITAL,dd=0;for(const t of closed.slice().sort((a,b)=>a.exitDate.localeCompare(b.exitDate))){eq+=t.pnl;peak=Math.max(peak,eq);dd=Math.min(dd,eq/peak-1)}return{n,pl,final:CAPITAL+pl,pf:gl?gw/gl:(gw?Infinity:0),wr:n?w.length/n:0,dd,avg:n?pl/n:0}}
function delayedEngine(rows,p,costSide,delay=0){
 const by=prep(rows),spy=by.SPY||[],symbols=TEST.filter(s=>by[s]?.length),spyMap=new Map(spy.map((r,i)=>[dateOf(r),i])),dates=[...new Set(rows.map(dateOf))].sort(),maps={};for(const s of symbols)maps[s]=new Map(by[s].map((r,i)=>[dateOf(r),i]));
 let cash=CAPITAL,pos={},closed=[],pending=[],blocked=0;
 for(let di=1;di<dates.length;di++){
  const date=dates[di],sigDate=dates[di-1];
  for(const s of Object.keys(pos)){const idx=maps[s].get(date);if(idx==null)continue;const bar=by[s][idx],q=pos[s],age=di-q.entryDI,stop=q.entryRaw*(1-p.stop),target=q.entryRaw*(1+p.target);let raw=null,why='';if(bar.l<=stop){raw=stop;why='stop'}else if(bar.h>=target){raw=target;why='target'}else if(age>=p.hold){raw=bar.c;why='maxhold'}if(raw!=null){const exit=raw*(1-costSide),value=q.shares*exit,pnl=value-q.cost;cash+=value;closed.push({symbol:s,entryDate:q.entryDate,exitDate:date,entry:q.entry,exit,entryRaw:q.entryRaw,shares:q.shares,pnl,ret:exit/q.entry-1,why});delete pos[s]}}
  const due=pending.filter(q=>q.entryDI===di);pending=pending.filter(q=>q.entryDI!==di);due.sort((a,b)=>b.score-a.score);for(const q of due){if(pos[q.s]||Object.keys(pos).length>=MAXPOS){blocked++;continue}const ti=maps[q.s].get(date);if(ti==null){blocked++;continue}const entryRaw=by[q.s][ti].o,mark=Object.values(pos).reduce((s,z)=>s+z.cost,0),eq=cash+mark,entry=entryRaw*(1+costSide),riskCash=eq*RISK,riskPerShare=Math.max(.0001,entryRaw*p.stop),shares=Math.min(riskCash/riskPerShare,(eq*MAXPOSPCT)/entry,cash/entry);if(!(shares>0)){blocked++;continue}const cost=shares*entry;if(cost>cash){blocked++;continue}cash-=cost;pos[q.s]={entryRaw,entry,shares,cost,entryDate:date,entryDI:di}}
  let cand=[];for(const s of symbols){if(pos[s]||pending.some(q=>q.s===s))continue;const si=maps[s].get(sigDate);if(si==null)continue;const a=by[s],need=Math.max(p.breakout+1,p.trend==='sma200'?205:p.trend==='sma100'?105:25,25);if(si<need)continue;const close=a[si].c,priorHigh=prevCloseHigh(a,si,p.breakout);if(!(priorHigh&&close>priorHigh))continue;if(p.trend!=='off'){const n=p.trend==='sma200'?200:100,ss=sma(a,si,n);if(!(ss&&close>ss))continue}if(p.volume!=='off'){const av=avgVol(a,si-1,20);if(!(av>0&&a[si].v>=av*p.volume))continue}if(p.regime!=='off'){const spi=spyMap.get(sigDate),n=p.regime==='spy200'?200:100;if(spi==null)continue;const ss=sma(spy,spi,n);if(!(ss&&spy[spi].c>ss))continue}const mom20=si>=20?close/a[si-20].c-1:0,breakoutPct=close/priorHigh-1;cand.push({s,score:mom20+breakoutPct*2})}
  cand.sort((a,b)=>b.score-a.score);const entryDI=di+delay;for(const c of cand){if(entryDI>=dates.length){blocked++;continue}if(delay===0){const ti=maps[c.s].get(date);if(ti==null)continue;pending.push({...c,entryDI:di});}else pending.push({...c,entryDI});}
  if(delay===0){const now=pending.filter(q=>q.entryDI===di);pending=pending.filter(q=>q.entryDI!==di);now.sort((a,b)=>b.score-a.score);for(const q of now){if(pos[q.s]||Object.keys(pos).length>=MAXPOS){blocked++;continue}const ti=maps[q.s].get(date);if(ti==null){blocked++;continue}const entryRaw=by[q.s][ti].o,mark=Object.values(pos).reduce((s,z)=>s+z.cost,0),eq=cash+mark,entry=entryRaw*(1+costSide),riskCash=eq*RISK,riskPerShare=Math.max(.0001,entryRaw*p.stop),shares=Math.min(riskCash/riskPerShare,(eq*MAXPOSPCT)/entry,cash/entry);if(!(shares>0))continue;const cost=shares*entry;if(cost>cash)continue;cash-=cost;pos[q.s]={entryRaw,entry,shares,cost,entryDate:date,entryDI:di}}}
 }
 const last=dates.at(-1);if(last)for(const s of Object.keys(pos)){const idx=maps[s].get(last);if(idx==null)continue;const q=pos[s],raw=by[s][idx].c,exit=raw*(1-costSide),value=q.shares*exit,pnl=value-q.cost;cash+=value;closed.push({symbol:s,entryDate:q.entryDate,exitDate:last,entry:q.entry,exit,entryRaw:q.entryRaw,shares:q.shares,pnl,ret:exit/q.entry-1,why:'periodend'})}
 return {...tradeStats(closed),closed,blocked,costSide,entryDelayTradingDays:delay};
}
function evaluate(rs){const qualifying=rs.filter(r=>r.pl>0&&r.pf>=1.05&&r.dd>=-.10).length,combined=rs.find(r=>r.id==='COMBINED'),pass=qualifying>=4&&combined&&combined.pl>0&&combined.pf>=1&&combined.dd>=-.12,holdCount=rs.filter(r=>r.pl>0&&r.pf>=1).length,hold=holdCount>=3&&rs.every(r=>r.dd>=-.15);return{verdict:pass?'PASS':hold?'HOLD':'FAIL',qualifyingPassScenarios:qualifying,qualifyingHoldScenarios:holdCount,combinedPass:!!(combined&&combined.pl>0&&combined.pf>=1&&combined.dd>=-.12),criteria:{pass:'4/5 P/L>0 PF>=1.05 DD>=-10%; COMBINED P/L>0 PF>=1.00 DD>=-12%',hold:'3/5 P/L>0 PF>=1.00; no DD<-15%'}}}
async function run(){const p=plan();if(!p?.locked||p.planHash!==PLAN_HASH)throw new Error('G5-planen måste vara låst med planhash '+PLAN_HASH+' före körning.');let x=load()||fresh();if(x.status==='complete')return x;if(!load()){await clearRows();save(x)}x.status='running';x.startedAt=x.startedAt||new Date().toISOString();if(!x.ledger.some(e=>e.event==='RESULT_OPEN'))x.ledger.push({at:new Date().toISOString(),event:'RESULT_OPEN',planHash:PLAN_HASH,candidate:CANDIDATE});save(x);try{const yy=years(),symbols=[...TEST,'SPY'];while(x.fetch.year<yy.length){const[a,b]=yy[x.fetch.year];while(x.fetch.symbol<symbols.length){const sym=symbols[x.fetch.symbol];emit('G5 STRESS TEST',`År ${x.fetch.year+1}/${yy.length} · symbol ${x.fetch.symbol+1}/${symbols.length} · ${sym}`);const rows=await fetchSymbol(sym,a,b);await putChunk(`${x.fetch.year}-${x.fetch.symbol}-${sym}`,rows);x.fetch.symbol++;save(x);await new Promise(r=>setTimeout(r,20))}x.fetch.year++;x.fetch.symbol=0;save(x)}const E=window.LinaG2Engine;if(!E?.normRows||!E?.engine)throw new Error('G2-motorn saknas.');const rows=E.normRows(await allRows());const rs=[];for(let i=0;i<SCENARIOS.length;i++){const s=SCENARIOS[i],cost=BASE_COST+s.extraCostPerSide;emit('BERÄKNAR G5',`${i+1}/5 · ${s.label}`);const r=s.entryDelayTradingDays?delayedEngine(rows,PARAMS,cost,s.entryDelayTradingDays):E.engine(rows,PARAMS,cost,TEST);rs.push({...s,totalCostPerSide:cost,n:r.n,pl:r.pl,pf:r.pf,wr:r.wr,dd:r.dd,avg:r.avg,final:r.final,closed:r.closed});await new Promise(r=>setTimeout(r,0))}const gate=evaluate(rs);x.scenarios=rs;x.gate=gate;x.status='complete';x.finishedAt=new Date().toISOString();x.providers=[...new Set(rows.map(z=>z.provider).filter(Boolean))];x.dataRows=rows.length;x.ledger.push({at:x.finishedAt,event:'GATE',verdict:gate.verdict,noRescue:true});delete x.fetch;save(x);await clearRows();emit('G5 KLART',gate.verdict);return x}catch(e){x=load()||x;x.status='error';x.lastError={at:new Date().toISOString(),message:e.message||String(e)};x.ledger.push({at:x.lastError.at,event:'RUN_ERROR',message:x.lastError.message});try{save(x)}catch{}emit('G5 KÖRFEL',x.lastError.message);throw e}}
function report(){const x=load();if(!x?.scenarios)return'G5-resultat saknas.';const f=n=>Number(n).toLocaleString('sv-SE',{maximumFractionDigits:2}),pct=n=>(100*n).toFixed(2)+'%';const L=['LINAS OPTI – G5 STRESS TEST','Clean Core: '+VERSION,'Handel: AVSTÄNGD','Plan: '+PLAN_HASH+' · kandidat '+CANDIDATE,'Period: '+START+' → '+END,'','GATE: '+x.gate.verdict,`PASS-kvalificerade scenarier: ${x.gate.qualifyingPassScenarios}/5`,`COMBINED villkor: ${x.gate.combinedPass?'JA':'NEJ'}`,'','SCENARIER'];x.scenarios.forEach(s=>L.push(`${s.id} · ${s.label} · ${s.n} affärer · P/L ${f(s.pl)} · PF ${Number.isFinite(s.pf)?f(s.pf):'∞'} · WR ${pct(s.wr)} · DD ${pct(s.dd)} · slut ${f(s.final)}`));L.push('','FORSKNINGSREGEL','Ingen rescue, parameterändring eller symbolrensning efter resultat. G5 är stress-/robusthetstest, inte ny oberoende OOS. G2/G3 Real Forward har högre evidens.');return L.join('\n')}
function dl(text,name,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportReport(){dl(report(),`LINAS_OPTI_G5_STRESS_V0217_${new Date().toISOString().slice(0,10)}.txt`)}
function exportRaw(){const x=load();if(x)dl(JSON.stringify(x,null,2),`LINAS_OPTI_G5_STRESS_RAW_V0217_${new Date().toISOString().slice(0,10)}.json`,'application/json')}
window.LinaG5Engine={VERSION,PLAN_HASH,CANDIDATE,SCENARIOS,load,run,report,exportReport,exportRaw,evaluate,delayedEngine};
})();
