(function(){
'use strict';
const VERSION='0.2.16',KEY='lina_clean_swing_g5_stress_plan_v0216',PLAN_HASH='6ec36eb2';
const SCENARIOS=[{"id":"COST_10","label":"Extra kostnad 0,10 % per sida","extraCostPerSide":0.001,"entryDelayTradingDays":0},{"id":"COST_25","label":"Extra kostnad 0,25 % per sida","extraCostPerSide":0.0025,"entryDelayTradingDays":0},{"id":"COST_50","label":"Extra kostnad 0,50 % per sida","extraCostPerSide":0.005,"entryDelayTradingDays":0},{"id":"DELAY_1","label":"Entry fördröjd 1 handelsdag","extraCostPerSide":0,"entryDelayTradingDays":1},{"id":"COMBINED","label":"0,25 % extra per sida + 1 handelsdags entryfördröjning","extraCostPerSide":0.0025,"entryDelayTradingDays":1}];
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
function lock(){let x=load();if(x?.locked)return x;x={schema:'LINA-G5-STRESS-PLAN-1',version:'V0.2.16',locked:true,planHash:PLAN_HASH,lockedAt:new Date().toISOString(),candidate:'15efd75a',sourceEvidence:'G4 PASS/FROZEN 95d2e735',period:['2020-01-01','2026-09-10'],universe:['AAPL','MSFT','AMZN','GOOGL','META','JPM','XOM','UNH','JNJ','PG','KO','CAT','HD','DIS','NKE','WMT'],scenarios:SCENARIOS,tradeEnabled:false,resultOpened:false};localStorage.setItem(KEY,JSON.stringify(x));return x}
function render(root,ctx){const x=load();const rows=SCENARIOS.map((s,i)=>`<div class="statusline"><b>${i+1}. ${s.label}</b></div>`).join('');root.innerHTML=`<div class="crumb">Dashboard › Forskning › Swing G5 Stress Test</div><section class="hero"><h1>G5 Stress Test</h1><p>Försöker slå sönder frysta Lina med sämre exekvering. Ingen parameterjakt. Handel AV.</p></section><button class="back" id="g5Back">← Forskning</button><section class="workspace"><div class="forward-lock"><b>${x?.locked?'🔒 G5 PLAN LÅST':'G5 PLAN FÖRREGISTRERAD'}</b><span>Plan ${PLAN_HASH} · kandidat 15efd75a · resultat ännu ej öppnat</span></div><h2>Frysta stresscenarier</h2>${rows}<div class="statusline"><b>Bas:</b> samma 16-symbolsuniversum och period 2020-01-01 → 2026-09-10 som frysta G4. G2-parametrarna ändras inte.</div><h2>Gate före resultat</h2><p><b>PASS:</b> minst 4/5 scenarier P/L &gt; 0, PF ≥1,05 och DD ≥−10 %. COMBINED måste dessutom ha P/L &gt; 0, PF ≥1,00 och DD ≥−12 %.</p><p><b>HOLD:</b> minst 3/5 scenarier P/L &gt; 0 och PF ≥1,00, och inget scenario DD &lt;−15 %. Annars FAIL.</p><div class="forward-note"><b>Forskningsregel:</b> ingen rescue, parameterändring eller symbolrensning efter resultat. V0.2.16 innehåller ingen G5-runner; planen måste låsas först.</div><div class="actions">${x?.locked?'<button class="secondary" disabled>✓ Plan låst · nästa release kör G5</button>':'<button id="g5Lock" class="primary">🔒 Lås G5-planen</button>'}</div></section>`;root.querySelector('#g5Back').onclick=ctx.back;const b=root.querySelector('#g5Lock');if(b)b.onclick=()=>{lock();render(root,ctx)}}
window.LinaG5={render,lock,load,PLAN_HASH};
})();
