(function(){
'use strict';
const VERSION='V0.2.25';
const RESULT_KEY='lina_clean_swing_g6_cost_boundary_result_v0224';
const DB_NAME='lina_g6_marketdata_v0224',STORE='chunks';
const PLAN_HASH='1567bbbe',CANDIDATE='15efd75a';
const START='2020-01-01',END='2026-09-10';
const TEST=['AAPL','MSFT','AMZN','GOOGL','META','JPM','XOM','UNH','JNJ','PG','KO','CAT','HD','DIS','NKE','WMT'];
const PARAMS={breakout:55,trend:'sma200',volume:1.5,regime:'spy200',stop:.07,target:.15,hold:10};
const BASE_COST=.001,CAPITAL=100000;
const GRID=[0,.0005,.001,.0015,.002,.0025,.003,.004,.005];
const API='https://linas-opti-api.mangaj73.workers.dev';
function load(){try{return JSON.parse(localStorage.getItem(RESULT_KEY)||'null')}catch{return null}}
function save(x){x.savedAt=new Date().toISOString();const s=JSON.stringify(x);if(s.length>350000)throw new Error('G6 compact state safety limit exceeded ('+s.length+' bytes).');try{localStorage.setItem(RESULT_KEY,s)}catch(e){throw new Error('G6 compact state could not be saved safely: '+(e.message||e))}document.dispatchEvent(new CustomEvent('lina:g6change'));return x}
function emit(stage,detail=''){document.dispatchEvent(new CustomEvent('lina:g6live',{detail:{stage,detail}}))}
function fresh(){return{schema:'LINA-SWING-G6-COST-BOUNDARY-RESULT-1',version:VERSION,planHash:PLAN_HASH,candidate:CANDIDATE,period:[START,END],universe:TEST,params:PARAMS,baseCostPerSide:BASE_COST,extraCostPerSideGrid:GRID,tradeEnabled:false,status:'ready',fetch:{year:0,symbol:0},points:null,gate:null,ledger:[],storage:{marketData:'IndexedDB',rawInLocalStorage:false}}}
function db(){return new Promise((res,rej)=>{const q=indexedDB.open(DB_NAME,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function putChunk(id,rows){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(rows,id);tx.oncomplete=()=>{d.close();res()};tx.onerror=()=>{d.close();rej(tx.error)}})}
async function allRows(){const d=await db();return new Promise((res,rej)=>{const q=d.transaction(STORE,'readonly').objectStore(STORE).getAll();q.onsuccess=()=>{d.close();res(q.result.flat())};q.onerror=()=>{d.close();rej(q.error)}})}
async function clearRows(){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();tx.oncomplete=()=>{d.close();res()};tx.onerror=()=>{d.close();rej(tx.error)}})}
function years(){const a=[];for(let y=2020;y<=2026;y++)a.push([`${y}-01-01`,y===2026?END:`${y}-12-31`]);return a}
async function bridge(path){const r=await fetch(API+path,{cache:'no-store'});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||('HTTP '+r.status));return j}
function rowsOf(j){return Array.isArray(j)?j:(j?.rows||j?.data||[])}
async function fetchSymbol(sym,a,b){const tries=[['Worker Yahoo daily',`/yahoo-bars?symbols=${encodeURIComponent(sym)}&timeframe=1Day&start=${a}&end=${b}`],['EODHD .US',`/eod-bars?symbols=${encodeURIComponent(sym+'.US')}&timeframe=1Day&start=${a}&end=${b}`],['Alpaca daily',`/bars?symbols=${encodeURIComponent(sym)}&timeframe=1Day&start=${a}T00:00:00Z&end=${b}T23:59:59Z`]];let errs=[];for(let cycle=1;cycle<=2;cycle++)for(const[name,path]of tries){try{emit('HÄMTAR G6',`${sym} · ${a} → ${b} · ${name} · försök ${cycle}/2`);const j=await Promise.race([bridge(path),new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout 60 s')),60000))]);const rows=rowsOf(j);if(!rows.length)throw new Error('0 dagsrader');return rows.map(r=>({...r,symbol:sym,s:sym,provider:name}))}catch(e){errs.push(`${name}: ${e.message||e}`)}}throw new Error(`${sym} ${a}–${b}: ${errs.slice(-3).join(' | ')}`)}
function evaluate(points){const valid=points.filter(r=>r.pl>0&&r.pf>=1);const boundary=valid.length?Math.max(...valid.map(r=>r.extraCostPerSide)):null;const through=boundary==null?[]:points.filter(r=>r.extraCostPerSide<=boundary);const anyDD15=points.some(r=>r.dd<-.15);const pass=boundary!=null&&boundary>=.002&&through.every(r=>r.dd>=-.10);const hold=!pass&&boundary!=null&&boundary>=.001&&boundary<.002&&!anyDD15;return{verdict:pass?'PASS':hold?'HOLD':'FAIL',boundaryExtraCostPerSide:boundary,boundaryTotalCostPerSide:boundary==null?null:BASE_COST+boundary,anyDDbelow15:anyDD15,criteria:{boundary:'Highest tested extra cost per side with P/L > 0 and PF >= 1.00; no interpolation',pass:'boundary >= 0.20% extra/side and DD >= -10% through boundary',hold:'boundary >= 0.10% and < 0.20%, no tested DD < -15%',fail:'boundary < 0.10%, or any tested DD < -15%'}}}
async function run(){let x=load()||fresh();if(x.planHash!==PLAN_HASH)throw new Error('G6 planhash mismatch. Kräver '+PLAN_HASH+'.');if(x.status==='complete')return x;if(!load()){await clearRows();save(x)}x.status='running';x.startedAt=x.startedAt||new Date().toISOString();if(!x.ledger.some(e=>e.event==='RESULT_OPEN'))x.ledger.push({at:new Date().toISOString(),event:'RESULT_OPEN',planHash:PLAN_HASH,candidate:CANDIDATE});save(x);try{const yy=years(),symbols=[...TEST,'SPY'];while(x.fetch.year<yy.length){const[a,b]=yy[x.fetch.year];while(x.fetch.symbol<symbols.length){const sym=symbols[x.fetch.symbol];emit('G6 COST BOUNDARY',`År ${x.fetch.year+1}/${yy.length} · symbol ${x.fetch.symbol+1}/${symbols.length} · ${sym}`);const rows=await fetchSymbol(sym,a,b);await putChunk(`${x.fetch.year}-${x.fetch.symbol}-${sym}`,rows);x.fetch.symbol++;save(x);await new Promise(r=>setTimeout(r,20))}x.fetch.year++;x.fetch.symbol=0;save(x)}const E=window.LinaG2Engine;if(!E?.normRows||!E?.engine)throw new Error('G2-motorn saknas.');const rows=E.normRows(await allRows());const points=[];for(let i=0;i<GRID.length;i++){const extra=GRID[i],cost=BASE_COST+extra;emit('BERÄKNAR G6',`${i+1}/${GRID.length} · extra ${(extra*100).toFixed(2)} %/sida`);const r=E.engine(rows,PARAMS,cost,TEST);points.push({extraCostPerSide:extra,totalCostPerSide:cost,n:r.n,pl:r.pl,pf:r.pf,wr:r.wr,dd:r.dd,avg:r.avg,final:r.final});await new Promise(r=>setTimeout(r,0))}x.points=points;x.gate=evaluate(points);x.status='complete';x.finishedAt=new Date().toISOString();x.providers=[...new Set(rows.map(z=>z.provider).filter(Boolean))];x.dataRows=rows.length;x.ledger.push({at:x.finishedAt,event:'GATE',verdict:x.gate.verdict,boundary:x.gate.boundaryExtraCostPerSide,noRescue:true});delete x.fetch;save(x);await clearRows();emit('G6 KLART',x.gate.verdict);return x}catch(e){x=load()||x;x.status='error';x.lastError={at:new Date().toISOString(),message:e.message||String(e)};x.ledger.push({at:x.lastError.at,event:'RUN_ERROR',message:x.lastError.message});try{save(x)}catch{}emit('G6 KÖRFEL',x.lastError.message);throw e}}
function report(){const x=load();if(!x?.points)return'G6-resultat saknas.';const f=n=>Number(n).toLocaleString('sv-SE',{maximumFractionDigits:2}),pct=n=>(100*n).toFixed(2)+'%',b=x.gate.boundaryExtraCostPerSide;const L=['LINAS OPTI – G6 EXECUTION COST BOUNDARY','Clean Core: '+VERSION,'Handel: AVSTÄNGD','Plan: '+PLAN_HASH+' · kandidat '+CANDIDATE,'Period: '+START+' → '+END,'','GATE: '+x.gate.verdict,'BOUNDARY extra kostnad/sida: '+(b==null?'ingen testpunkt':pct(b)),'','TESTPUNKTER'];x.points.forEach(s=>L.push(`Extra ${pct(s.extraCostPerSide)} · total ${pct(s.totalCostPerSide)} · ${s.n} affärer · P/L ${f(s.pl)} · PF ${Number.isFinite(s.pf)?f(s.pf):'∞'} · WR ${pct(s.wr)} · DD ${pct(s.dd)} · slut ${f(s.final)}`));L.push('','FORSKNINGSREGEL','G6 beskriver kostnadskänslighet. Ingen parameterändring, symbolrensning eller rescue av G5. G6 är inte ny oberoende OOS-evidens. G2/G3 Real Forward har högre evidens.');return L.join('\n')}
function dl(text,name,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportReport(){dl(report(),`LINAS_OPTI_G6_COST_BOUNDARY_V0224_${new Date().toISOString().slice(0,10)}.txt`)}
function exportRaw(){const x=load();if(x)dl(JSON.stringify(x,null,2),`LINAS_OPTI_G6_COST_BOUNDARY_RAW_V0224_${new Date().toISOString().slice(0,10)}.json`,'application/json')}
window.LinaG6Engine={VERSION,PLAN_HASH,CANDIDATE,GRID,load,run,report,exportReport,exportRaw,evaluate};
})();
