(function(){
'use strict';
const VERSION='V0.2.49', PLAN_HASH='1d5f8bc1', RUNNER_SPEC_HASH='c7f6a2d9';
const KEY='lina_clean_gen2_engine_v0246', DB='lina_gen2_market_v1', STORE='bars';
const WINDOWS=Object.freeze({development:Object.freeze(['2020-01-01','2022-12-31']),validation:Object.freeze(['2023-01-01','2024-12-31'])});
const SEALED_HOLDOUT=Object.freeze(['2025-01-01','2026-09-10']);
const SYMBOLS=Object.freeze(['AMD','SHOP','ADBE','MU','FDX','TSLA','LUV','NFLX','C','NOW','QCOM','BAC','GM','DDOG','PYPL','NVDA']);
const FAMILIES=Object.freeze(['Trend/momentum','Mean reversion','Volatility breakout','Regime ensemble']);
const SPEC=Object.freeze({schema:'LINA-GEN2-RUNNER-SPEC-1',planHash:PLAN_HASH,universe:SYMBOLS,costSide:.001,capital:100000,maxPositions:5,maxPositionPct:.20,riskPerTrade:.005,
 grids:{trend:[{lookback:20,trend:100,hold:10},{lookback:55,trend:100,hold:15},{lookback:55,trend:200,hold:20},{lookback:100,trend:200,hold:20}],mean:[{rsi:25,trend:100,hold:5},{rsi:30,trend:100,hold:7},{rsi:25,trend:200,hold:7},{rsi:30,trend:200,hold:10}],vol:[{lookback:20,atr:1.2,hold:10},{lookback:20,atr:1.5,hold:10},{lookback:55,atr:1.2,hold:15},{lookback:55,atr:1.5,hold:15}],ensemble:[{trendWeight:.5,meanWeight:.25,volWeight:.25},{trendWeight:.4,meanWeight:.3,volWeight:.3},{trendWeight:.6,meanWeight:.2,volWeight:.2}]},
 selection:{minimumTrades:80,profitFactor:1.20,maxDrawdown:.12,positiveValidation:true,concentrationGuard:{maxSingleSymbolGrossProfitShare:.40},ranking:'validation PF + drawdown + concentration; P/L is not primary'}});
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
function save(x){x.savedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(x));emit();return x}
function emit(){document.dispatchEvent(new CustomEvent('lina:gen2change'))}
function fresh(){return{schema:'LINA-GEN2-ENGINE-2',version:VERSION,planHash:PLAN_HASH,runnerSpecHash:RUNNER_SPEC_HASH,runnerSpecLocked:false,tradeEnabled:false,holdoutOpened:false,holdoutResults:null,status:'SPEC_NOT_LOCKED',runs:[],familyResults:{},negativeResults:[],candidate:null}}
function assertPlan(){const L=window.LinaGen2Lab,x=L?.load?.();if(!L||L.PLAN_HASH!==PLAN_HASH||!x?.locked||x.planHash!==PLAN_HASH)throw new Error('BLOCKERAD: Gen2-plan 1d5f8bc1 är inte verifierat låst');if(x.holdoutOpened===true)throw new Error('BLOCKERAD: planstate anger öppnad holdout');return x}
function assertWindow(name,start,end){const w=WINDOWS[name];if(!w)throw new Error('BLOCKERAD: endast DEV och Validation är tillåtna');if(start!==w[0]||end!==w[1])throw new Error('BLOCKERAD: intervallet avviker från förregistreringen');if(start>=SEALED_HOLDOUT[0]||end>=SEALED_HOLDOUT[0])throw new Error('BLOCKERAD: holdout är SEALED')}
function init(){assertPlan();let x=load()||fresh();if(x.planHash!==PLAN_HASH||x.tradeEnabled!==false||x.holdoutOpened!==false||x.holdoutResults!=null)throw new Error('BLOCKERAD: engine-state bryter mot låset');return save(x)}
function lockRunnerSpec(){let x=init();if(x.runnerSpecLocked&&x.runnerSpecHash!==RUNNER_SPEC_HASH)throw new Error('BLOCKERAD: annat runnerspec är redan låst');x.runnerSpecLocked=true;x.runnerSpecHash=RUNNER_SPEC_HASH;x.runnerSpecLockedAt=x.runnerSpecLockedAt||new Date().toISOString();x.status='READY_FOR_DEV';return save(x)}
function preflight(){const x=init();assertWindow('development',...WINDOWS.development);assertWindow('validation',...WINDOWS.validation);return{ok:true,version:VERSION,planHash:PLAN_HASH,runnerSpecHash:RUNNER_SPEC_HASH,runnerSpecLocked:x.runnerSpecLocked,holdout:'SEALED',tradeEnabled:false}}
function db(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>q.result.createObjectStore(STORE);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function cachePut(k,v){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(v,k);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
async function cacheGet(k){const d=await db();return new Promise((res,rej)=>{const q=d.transaction(STORE).objectStore(STORE).get(k);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)})}
function rowsOf(j){return Array.isArray(j)?j:(j?.rows||j?.data||[])}
function norm(rows,sym){return rows.map(r=>({s:sym,d:String(r.t||r.time||r.timestamp||'').slice(0,10),o:+r.o,h:+r.h,l:+r.l,c:+r.c,v:+(r.v||0)})).filter(r=>r.d&&[r.o,r.h,r.l,r.c].every(Number.isFinite)).sort((a,b)=>a.d.localeCompare(b.d))}
async function fetchSym(sym,a,b){const k=`${sym}:${a}:${b}`,old=await cacheGet(k);if(old?.length)return old;const base=window.LinaAPI.workerBase, tries=[`/yahoo-bars?symbols=${encodeURIComponent(sym)}&timeframe=1Day&start=${a}&end=${b}`,`/eod-bars?symbols=${encodeURIComponent(sym+'.US')}&timeframe=1Day&start=${a}&end=${b}`,`/bars?symbols=${encodeURIComponent(sym)}&timeframe=1Day&start=${a}T00:00:00Z&end=${b}T23:59:59Z`];let err;for(const path of tries){try{const r=await fetch(base+path,{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error||'HTTP '+r.status);const z=norm(rowsOf(j),sym);if(z.length){await cachePut(k,z);return z}}catch(e){err=e}}throw Error(`${sym}: ${err?.message||'ingen data'}`)}
async function data(a,b){const out={};for(let i=0;i<SYMBOLS.length;i++){progress(`Data ${i+1}/${SYMBOLS.length} · ${SYMBOLS[i]}`);out[SYMBOLS[i]]=await fetchSym(SYMBOLS[i],a,b)}return out}
function sma(a,i,n){if(i<n-1)return null;let s=0;for(let k=i-n+1;k<=i;k++)s+=a[k].c;return s/n}
function rsi(a,i,n=14){if(i<n)return null;let g=0,l=0;for(let k=i-n+1;k<=i;k++){const q=a[k].c-a[k-1].c;q>=0?g+=q:l-=q}if(!l)return 100;const rs=(g/n)/(l/n);return 100-100/(1+rs)}
function atr(a,i,n=14){if(i<n)return null;let s=0;for(let k=i-n+1;k<=i;k++)s+=Math.max(a[k].h-a[k].l,Math.abs(a[k].h-a[k-1].c),Math.abs(a[k].l-a[k-1].c));return s/n}
function high(a,i,n){if(i<n)return null;let h=-Infinity;for(let k=i-n;k<i;k++)h=Math.max(h,a[k].c);return h}
function signal(f,a,i,p){if(i<210)return false;const c=a[i].c;if(f==='Trend/momentum')return c>high(a,i,p.lookback)&&c>sma(a,i,p.trend);if(f==='Mean reversion')return c>sma(a,i,p.trend)&&rsi(a,i,14)<=p.rsi;if(f==='Volatility breakout'){const A=atr(a,i-1,14);return c>high(a,i,p.lookback)&&(a[i].h-a[i].l)>=A*p.atr}return false}
function stats(tr){const n=tr.length,gp=tr.filter(t=>t.pnl>0).reduce((s,t)=>s+t.pnl,0),gl=-tr.filter(t=>t.pnl<0).reduce((s,t)=>s+t.pnl,0),pl=tr.reduce((s,t)=>s+t.pnl,0);let eq=100000,pk=eq,dd=0;for(const t of tr.slice().sort((a,b)=>a.exit.localeCompare(b.exit))){eq+=t.pnl;pk=Math.max(pk,eq);dd=Math.min(dd,eq/pk-1)}const by={};for(const t of tr)by[t.s]=(by[t.s]||0)+Math.max(0,t.pnl);const maxShare=gp?Math.max(0,...Object.values(by))/gp:1;return{n,pl,pf:gl?gp/gl:(gp?99:0),dd,wr:n?tr.filter(t=>t.pnl>0).length/n:0,maxSymbolGrossProfitShare:maxShare}}
function testFamily(f,by,p){let tr=[];for(const [s,a] of Object.entries(by)){for(let i=210;i<a.length-1;i++){if(!signal(f,a,i,p))continue;const entry=a[i+1].o*1.001,exitI=Math.min(a.length-1,i+1+p.hold),exit=a[exitI].c*.999;tr.push({s,entry:a[i+1].d,exit:a[exitI].d,pnl:Math.min(20000,500/(Math.max(.01,entry*.05)))* (exit-entry)});i=exitI-1}}return stats(tr)}
function ensemble(by,p){const parts=[['Trend/momentum',{lookback:55,trend:200,hold:20},p.trendWeight],['Mean reversion',{rsi:30,trend:200,hold:10},p.meanWeight],['Volatility breakout',{lookback:55,atr:1.2,hold:15},p.volWeight]];let rs=parts.map(([f,q,w])=>({w,r:testFamily(f,by,q)}));return{n:Math.round(rs.reduce((s,x)=>s+x.r.n*x.w,0)),pl:rs.reduce((s,x)=>s+x.r.pl*x.w,0),pf:rs.reduce((s,x)=>s+x.r.pf*x.w,0),dd:rs.reduce((s,x)=>s+x.r.dd*x.w,0),wr:rs.reduce((s,x)=>s+x.r.wr*x.w,0),maxSymbolGrossProfitShare:Math.max(...rs.map(x=>x.r.maxSymbolGrossProfitShare))}}
function gridFor(f){return f==='Trend/momentum'?SPEC.grids.trend:f==='Mean reversion'?SPEC.grids.mean:f==='Volatility breakout'?SPEC.grids.vol:SPEC.grids.ensemble}
function evalOne(f,by,p){return f==='Regime ensemble'?ensemble(by,p):testFamily(f,by,p)}
function qualifies(r){return r.n>=SPEC.selection.minimumTrades&&r.pf>=SPEC.selection.profitFactor&&Math.abs(r.dd)<=SPEC.selection.maxDrawdown&&r.pl>0&&r.maxSymbolGrossProfitShare<=SPEC.selection.concentrationGuard.maxSingleSymbolGrossProfitShare}
function rank(r){return r.pf*100-Math.abs(r.dd)*150-r.maxSymbolGrossProfitShare*25+Math.min(r.n,200)/20}
function progress(text){document.dispatchEvent(new CustomEvent('lina:gen2progress',{detail:{text}}))}
async function runFamily(f){assertPlan();let x=init();if(!x.runnerSpecLocked)throw Error('Lås runnerspec före första körning');if(!FAMILIES.includes(f))throw Error('Okänd familj');const dev=await data(...WINDOWS.development),val=await data(...WINDOWS.validation),rows=[];for(const p of gridFor(f)){progress(`${f} · ${rows.length+1}/${gridFor(f).length}`);const d=evalOne(f,dev,p),v=evalOne(f,val,p);rows.push({params:p,dev:d,validation:v,eligible:qualifies({...v,n:d.n+v.n})&&v.pl>0,score:rank(v)})}rows.sort((a,b)=>b.score-a.score);const best=rows[0];x=load();x.runs.push({at:new Date().toISOString(),family:f,trials:rows.length});x.familyResults[f]={status:best?.eligible?'PASS':'FAIL',trials:rows.length,best};if(!best?.eligible)x.negativeResults.push({at:new Date().toISOString(),family:f,status:'FAIL',reason:'Ingen variant klarade låsta minimikrav'});x.status='DEV_VALIDATION_RUNNING';save(x);return x.familyResults[f]}
function report(){const x=load()||fresh(),L=['LINAS OPTI – GENERATION 2 DEV/VALIDATION','Release: '+VERSION,'Plan: '+PLAN_HASH,'Runner spec: '+RUNNER_SPEC_HASH,'Handel: AV','Holdout: SEALED','','Familjer'];for(const f of FAMILIES){const z=x.familyResults[f];L.push(`${f}: ${z?z.status+' · '+z.trials+' trials · DEV '+JSON.stringify(z.best?.dev)+' · VAL '+JSON.stringify(z.best?.validation):'EJ KÖRD'}`)}L.push('','Negativa resultat bevarade: '+x.negativeResults.length,'Holdoutresultat: INGA');return L.join('\n')}
window.LinaGen2Engine={VERSION,PLAN_HASH,RUNNER_SPEC_HASH,SPEC,WINDOWS,SEALED_HOLDOUT,FAMILIES,load,init,lockRunnerSpec,preflight,runFamily,report,assertWindow};
})();