(function(){
'use strict';
const VERSION='V0.2.57';
const KEY='lina_clean_gen3_plan_v0257';
const PLAN=Object.freeze({
 schema:'LINA-GEN3-PREREG-1',generation:'Lina Generation 3',tradeEnabled:false,
 purpose:'Ny generation efter avslutad Gen2. Inte rescue av Gen2.',
 lessons:Object.freeze(['Gen2 Holdout är permanent observerad och får aldrig återanvändas som osedd holdout.','Gen2 föll på 45 affärer mot låst minimikrav 80 trots positiv P/L, PF 1.65 och DD 7.5%.','Gen3 får använda lärdomen för att formulera en NY hypotes, men får inte ändra Gen2 eller dess evidens.']),
 hypothesis:'Testa om högre signal-/affärsfrekvens kan uppnås utan att sänka de tidigare risk- och kvalitetskraven.',
 historicalUse:Object.freeze({research:'2020-01-01 → 2024-12-31',method:'walk-forward/resampling; all denna historik betraktas som observerad forskning, inte ny holdout',observedDiagnostic:'2025-01-01 → 2026-09-10 är observerad Gen2-historik och får inte användas som ny holdout'}),
 forward:Object.freeze({start:'2026-09-18',mode:'FORWARD ONLY',rule:'Kandidat och runnerspec måste frysas + GitHub-verifieras före första forward-observation. Ingen retroaktiv start.'}),
 families:Object.freeze(['Kortare trend/momentum','Trend-pullback','Multi-timeframe momentum','Diversifierad regime ensemble']),
 gates:Object.freeze({profitFactor:1.20,maxDrawdownPct:12,positiveOOS:true,maxSingleSymbolGrossProfitSharePct:40,minimumOOSTrades:100,foldRule:'positiv i minst 3 av 4 walk-forward-folds'}),
 invariants:Object.freeze(['Handel AV','Ingen användning av Gen2 Holdout som ny holdout','Ingen sänkning av PF/DD/koncentrationskrav för att rädda Gen2','Alla varianter sparas före nästa steg','Negativa resultat bevaras','Permanent state/evidens GitHub-first'])
});
const EXPECTED_HASH='fa55540a';
function canonical(o){if(Array.isArray(o))return '['+o.map(canonical).join(',')+']';if(o&&typeof o==='object')return '{'+Object.keys(o).sort().map(k=>JSON.stringify(k)+':'+canonical(o[k])).join(',')+'}';return JSON.stringify(o)}
function fnv(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')}
const PLAN_HASH=fnv(canonical(PLAN));
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
function lock(){if(PLAN_HASH!==EXPECTED_HASH)throw Error('BLOCKERAD: Gen3-planens hash avviker');let x=load();if(x?.locked){if(x.planHash!==EXPECTED_HASH)throw Error('BLOCKERAD: befintligt Gen3-lås har fel hash');return x}x={schema:'LINA-GEN3-PLAN-LOCK-1',release:VERSION,locked:true,lockedAt:new Date().toISOString(),planHash:EXPECTED_HASH,tradeEnabled:false,status:'PLAN_LOCKED_RUNNER_NOT_BUILT'};localStorage.setItem(KEY,JSON.stringify(x));window.LinaGitHubSync?.queueSync?.();return x}
function render(root,ctx){const x=load(),locked=Boolean(x?.locked&&x.planHash===EXPECTED_HASH&&PLAN_HASH===EXPECTED_HASH);root.innerHTML=`<div class="crumb">Dashboard › Forskning › Lina Generation 3</div><section class="hero"><h1>🧪 Lina Generation 3</h1><p>Ny förregistrerad generation efter Gen2. Gen2 ändras inte och dess Holdout får aldrig bli "osedd" igen.</p></section><button class="back" id="back">← Forskning</button><section class="workspace"><div class="forward-lock"><b>${locked?'🔒 GEN 3 PLAN LÅST':'GEN 3 PLAN · EJ LÅST'}</b><span>Plan ${PLAN_HASH} · Handel AV</span></div><div class="forward-note"><b>Varför en ny generation?</b> Gen2 gav positivt Holdout-resultat men FAIL på det låsta aktivitetskravet: 45 affärer mot minst 80. Vi räddar inte Gen2. I stället formuleras en ny hypotes: högre affärsfrekvens utan att sänka PF-, DD- eller koncentrationskraven.</div><h2>Datadisciplin</h2><div class="statusline"><b>Observerad historik:</b> 2020–2024 används endast som forsknings-/walk-forward-material.<br><b>Gen2-period 2025-01-01 → 2026-09-10:</b> redan observerad och förbjuden som ny Holdout.<br><b>Nästa verkligt osedda prov:</b> FORWARD ONLY från 2026-09-18, efter framtida kandidatfrysning.</div><h2>Förregistrerade familjer</h2>${PLAN.families.map(f=>`<div class="statusline"><b>${f}</b><br><small>Designad för ny hypotes; runner byggs först efter planlås.</small></div>`).join('')}<h2>Låsta kvalitetskrav</h2><div class="forward-note">Intern OOS: ≥100 affärer · PF ≥1,20 · DD ≤12 % · positiv OOS · max 40 % gross profit från en symbol · positiv i minst 3 av 4 walk-forward-folds.</div><div class="forward-note"><b>Viktig spärr:</b> detta är inte ett nytt historiskt Holdout. Slutlig bekräftelse måste komma från framtida data som inte existerade när planen låstes.</div><div class="actions">${locked?'<button class="secondary" disabled>✓ Plan låst · nästa byggsteg är runnerspec + engine</button>':'<button id="lock" class="primary">🔒 Lås Gen3-plan</button>'}</div></section>`;root.querySelector('#back').onclick=ctx.back;root.querySelector('#lock')?.addEventListener('click',()=>{lock();render(root,ctx)})}
window.LinaGen3={VERSION,PLAN,PLAN_HASH,EXPECTED_HASH,load,lock,render};
})();
