(function(){
'use strict';
const VERSION='V0.2.59', PLAN_HASH='fa55540a';
const KEY='lina_clean_gen3_engine_v0258', DB='lina_gen3_market_v1', STORE='bars';
const SYMBOLS=Object.freeze(['AMD','SHOP','ADBE','MU','FDX','TSLA','LUV','NFLX','C','NOW','QCOM','BAC','GM','DDOG','PYPL','NVDA']);
const FAMILIES=Object.freeze(['Kortare trend/momentum','Trend-pullback','Multi-timeframe momentum','Diversifierad regime ensemble']);
const FOLDS=Object.freeze([
 Object.freeze({train:['2020-01-01','2020-12-31'],oos:['2021-01-01','2021-12-31']}),
 Object.freeze({train:['2020-01-01','2021-12-31'],oos:['2022-01-01','2022-12-31']}),
 Object.freeze({train:['2020-01-01','2022-12-31'],oos:['2023-01-01','2023-12-31']}),
 Object.freeze({train:['2020-01-01','2023-12-31'],oos:['2024-01-01','2024-12-31']})
]);
const SPEC=Object.freeze({schema:'LINA-GEN3-RUNNER-SPEC-1',planHash:PLAN_HASH,universe:SYMBOLS,costSide:.001,capital:100000,maxPositions:5,maxPositionPct:.20,riskPerTrade:.005,
 grids:Object.freeze({
  shortTrend:Object.freeze([{lookback:10,trend:50,hold:5},{lookback:15,trend:75,hold:7},{lookback:20,trend:100,hold:7},{lookback:30,trend:100,hold:10}]),
  pullback:Object.freeze([{trend:100,pullback:5,hold:5},{trend:100,pullback:10,hold:7},{trend:150,pullback:5,hold:7},{trend:200,pullback:10,hold:10}]),
  mtf:Object.freeze([{fast:20,slow:100,mom:10,hold:7},{fast:30,slow:120,mom:15,hold:10},{fast:50,slow:150,mom:20,hold:10},{fast:50,slow:200,mom:30,hold:15}]),
  ensemble:Object.freeze([{trendWeight:.50,pullWeight:.25,mtfWeight:.25},{trendWeight:.40,pullWeight:.30,mtfWeight:.30},{trendWeight:.60,pullWeight:.20,mtfWeight:.20}])
 }),selection:Object.freeze({minimumOOSTrades:100,profitFactor:1.20,maxDrawdown:.12,positiveOOS:true,maxSingleSymbolGrossProfitShare:.40,minimumPositiveFolds:3,ranking:'OOS PF + fold stability + drawdown + concentration; P/L is not primary'})});
function canonical(o){if(Array.isArray(o))return '['+o.map(canonical).join(',')+']';if(o&&typeof o==='object')return '{'+Object.keys(o).sort().map(k=>JSON.stringify(k)+':'+canonical(o[k])).join(',')+'}';return JSON.stringify(o)}
function fnv(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')}
const RUNNER_SPEC_HASH=fnv(canonical(SPEC));
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
function save(x){x.savedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(x));document.dispatchEvent(new CustomEvent('lina:gen3change'));window.LinaGitHubSync?.queueSync?.();return x}
function fresh(){return{schema:'LINA-GEN3-ENGINE-1',version:VERSION,planHash:PLAN_HASH,runnerSpecHash:RUNNER_SPEC_HASH,runnerSpecLocked:false,tradeEnabled:false,status:'SPEC_NOT_LOCKED',runs:[],familyResults:{},negativeResults:[],candidate:null,forwardOpened:false}}
function assertPlan(){const L=window.LinaGen3,x=L?.load?.();if(!L||L.PLAN_HASH!==PLAN_HASH||!x?.locked||x.planHash!==PLAN_HASH)throw Error('BLOCKERAD: Gen3-plan fa55540a är inte verifierat låst');return x}
function init(){assertPlan();let x=load()||fresh();if(x.planHash!==PLAN_HASH||x.tradeEnabled!==false||x.forwardOpened===true)throw Error('BLOCKERAD: Gen3 engine-state bryter mot låset');return save(x)}
function lockRunnerSpec(){let x=init();if(x.runnerSpecLocked&&x.runnerSpecHash!==RUNNER_SPEC_HASH)throw Error('BLOCKERAD: annat Gen3-runnerspec är redan låst');x.runnerSpecLocked=true;x.runnerSpecLockedAt=x.runnerSpecLockedAt||new Date().toISOString();x.status='READY_FOR_RESEARCH';return save(x)}
function preflight(){const x=init();return{ok:true,version:VERSION,planHash:PLAN_HASH,runnerSpecHash:RUNNER_SPEC_HASH,runnerSpecLocked:x.runnerSpecLocked,history:'2020-2024 OBSERVERAD',forward:'SEALED UNTIL FUTURE CANDIDATE FREEZE',tradeEnabled:false}}
function db(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>q.result.createObjectStore(STORE);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function cachePut(k,v){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(v,k);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
async function cacheGet(k){const d=await db();return new Promise((res,rej)=>{const q=d.transaction(STORE).objectStore(STORE).get(k);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)})}
function rowsOf(j){return Array.isArray(j)?j:(j?.rows||j?.data||[])}
function norm(rows,sym){return rows.map(r=>({s:sym,d:String(r.t||r.time||r.timestamp||'').slice(0,10),o:+r.o,h:+r.h,l:+r.l,c:+r.c,v:+(r.v||0)})).filter(r=>r.d&&[r.o,r.h,r.l,r.c].every(Number.isFinite)).sort((a,b)=>a.d.localeCompare(b.d))}
async function fetchSym(sym,a,b){if(b>'2024-12-31')throw Error('BLOCKERAD: Gen3 research-engine får inte läsa data efter 2024-12-31');const k=`${sym}:${a}:${b}`,old=await cacheGet(k);if(old?.length)return old;const base=window.LinaAPI.workerBase,tries=[`/yahoo-bars?symbols=${encodeURIComponent(sym)}&timeframe=1Day&start=${a}&end=${b}`,`/eod-bars?symbols=${encodeURIComponent(sym+'.US')}&timeframe=1Day&start=${a}&end=${b}`,`/bars?symbols=${encodeURIComponent(sym)}&timeframe=1Day&start=${a}T00:00:00Z&end=${b}T23:59:59Z`];let err;for(const path of tries){try{const r=await fetch(base+path,{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error||'HTTP '+r.status);const z=norm(rowsOf(j),sym);if(z.length){await cachePut(k,z);return z}}catch(e){err=e}}throw Error(`${sym}: ${err?.message||'ingen data'}`)}
async function data(a,b){const out={};for(let i=0;i<SYMBOLS.length;i++){progress(`Data ${i+1}/${SYMBOLS.length} · ${SYMBOLS[i]}`);out[SYMBOLS[i]]=await fetchSym(SYMBOLS[i],a,b)}return out}
function sma(a,i,n){if(i<n-1)return null;let s=0;for(let k=i-n+1;k<=i;k++)s+=a[k].c;return s/n}
function high(a,i,n){if(i<n)return null;let h=-Infinity;for(let k=i-n;k<i;k++)h=Math.max(h,a[k].c);return h}
function signal(f,a,i,p){if(i<205)return false;const c=a[i].c;if(f==='Kortare trend/momentum')return c>high(a,i,p.lookback)&&c>sma(a,i,p.trend);if(f==='Trend-pullback'){const tr=sma(a,i,p.trend),recent=high(a,i,p.pullback);return c>tr&&c<recent&&c>a[i-1].c}if(f==='Multi-timeframe momentum'){const fast=sma(a,i,p.fast),slow=sma(a,i,p.slow);return c>fast&&fast>slow&&c>a[Math.max(0,i-p.mom)].c}return false}
function stats(tr){const n=tr.length,gp=tr.filter(t=>t.pnl>0).reduce((s,t)=>s+t.pnl,0),gl=-tr.filter(t=>t.pnl<0).reduce((s,t)=>s+t.pnl,0),pl=tr.reduce((s,t)=>s+t.pnl,0);let eq=100000,pk=eq,dd=0;for(const t of tr.slice().sort((a,b)=>a.exit.localeCompare(b.exit))){eq+=t.pnl;pk=Math.max(pk,eq);dd=Math.min(dd,eq/pk-1)}const by={};for(const t of tr)by[t.s]=(by[t.s]||0)+Math.max(0,t.pnl);return{n,pl,pf:gl?gp/gl:(gp?99:0),dd,wr:n?tr.filter(t=>t.pnl>0).length/n:0,maxSymbolGrossProfitShare:gp?Math.max(0,...Object.values(by))/gp:1}}
function testFamily(f,by,p){let tr=[];for(const [s,a] of Object.entries(by)){for(let i=205;i<a.length-1;i++){if(!signal(f,a,i,p))continue;const entry=a[i+1].o*1.001,exitI=Math.min(a.length-1,i+1+p.hold),exit=a[exitI].c*.999;tr.push({s,entry:a[i+1].d,exit:a[exitI].d,pnl:Math.min(20000,500/Math.max(.01,entry*.05))*(exit-entry)});i=exitI-1}}return stats(tr)}
function ensemble(by,p){const parts=[['Kortare trend/momentum',{lookback:20,trend:100,hold:7},p.trendWeight],['Trend-pullback',{trend:150,pullback:5,hold:7},p.pullWeight],['Multi-timeframe momentum',{fast:50,slow:150,mom:20,hold:10},p.mtfWeight]];const rs=parts.map(([f,q,w])=>({w,r:testFamily(f,by,q)}));return{n:Math.round(rs.reduce((s,x)=>s+x.r.n*x.w,0)),pl:rs.reduce((s,x)=>s+x.r.pl*x.w,0),pf:rs.reduce((s,x)=>s+x.r.pf*x.w,0),dd:rs.reduce((s,x)=>s+x.r.dd*x.w,0),wr:rs.reduce((s,x)=>s+x.r.wr*x.w,0),maxSymbolGrossProfitShare:Math.max(...rs.map(x=>x.r.maxSymbolGrossProfitShare))}}
function gridFor(f){return f===FAMILIES[0]?SPEC.grids.shortTrend:f===FAMILIES[1]?SPEC.grids.pullback:f===FAMILIES[2]?SPEC.grids.mtf:SPEC.grids.ensemble}
function evalOne(f,by,p){return f===FAMILIES[3]?ensemble(by,p):testFamily(f,by,p)}
function aggregate(folds){const n=folds.reduce((s,x)=>s+x.n,0),pl=folds.reduce((s,x)=>s+x.pl,0),gpProxy=folds.reduce((s,x)=>s+Math.max(0,x.pl),0),pf=folds.reduce((s,x)=>s+x.pf*Math.max(1,x.n),0)/Math.max(1,n);return{n,pl,pf,dd:Math.min(...folds.map(x=>x.dd)),maxSymbolGrossProfitShare:Math.max(...folds.map(x=>x.maxSymbolGrossProfitShare)),positiveFolds:folds.filter(x=>x.pl>0).length,gpProxy}}
function qualifies(r){return r.n>=SPEC.selection.minimumOOSTrades&&r.pf>=SPEC.selection.profitFactor&&Math.abs(r.dd)<=SPEC.selection.maxDrawdown&&r.pl>0&&r.maxSymbolGrossProfitShare<=SPEC.selection.maxSingleSymbolGrossProfitShare&&r.positiveFolds>=SPEC.selection.minimumPositiveFolds}
function rank(r){return r.pf*100+r.positiveFolds*20-Math.abs(r.dd)*150-r.maxSymbolGrossProfitShare*25+Math.min(r.n,250)/25}
function progress(text){document.dispatchEvent(new CustomEvent('lina:gen3progress',{detail:{text}}))}
async function persistEvidence(f,result,at){const E=window.LinaEvidence;if(!E?.stage||!E?.approveAndSync)return{status:'LOKALT SPARAD · EVIDENCE-MODUL SAKNAS'};const safe=f.toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,''),name=`LINAS_GEN3_${safe}_WALK_FORWARD_ALL_VARIANTS_${at.slice(0,10)}.json`;const artifact={schema:'LINA-GEN3-WALK-FORWARD-EVIDENCE-1',release:VERSION,createdAt:at,planHash:PLAN_HASH,runnerSpecHash:RUNNER_SPEC_HASH,family:f,folds:FOLDS,observedHistoryOnly:true,forward:'NOT OPENED',tradeEnabled:false,trials:result.trials,status:result.status,variants:result.variants};const item=E.stage(name,JSON.stringify(artifact,null,2),'application/json','Lina Gen3');if(!item?.id)return{status:'LOKALT SPARAD · EVIDENCE STAGING FAIL'};const r=await E.approveAndSync(item.id);return{status:r?.status||'FROZEN',name,githubPath:r?.githubPath||null,githubCommit:r?.githubCommit||null}}
async function runFamily(f){assertPlan();let x=init();if(!x.runnerSpecLocked)throw Error('Lås Gen3-runnerspec före första körning');if(!FAMILIES.includes(f))throw Error('Okänd familj');if(x.familyResults?.[f])throw Error('BLOCKERAD: familjen är redan körd; evidens får inte skrivas över');const foldData=[];for(let i=0;i<FOLDS.length;i++){progress(`${f} · fold ${i+1}/4 · hämtar OOS ${FOLDS[i].oos[0].slice(0,4)}`);foldData.push(await data(...FOLDS[i].oos))}const variants=[];for(const p of gridFor(f)){const results=foldData.map(by=>evalOne(f,by,p)),agg=aggregate(results);variants.push({params:p,folds:results,oos:agg,eligible:qualifies(agg),score:rank(agg)})}variants.sort((a,b)=>b.score-a.score);const best=variants[0],at=new Date().toISOString();x=load();x.runs.push({at,family:f,trials:variants.length,allVariantsStored:true,folds:4});x.familyResults[f]={status:best?.eligible?'PASS':'FAIL',trials:variants.length,best,variants,evidence:{status:'LOKALT SPARAD · SYNK PÅGÅR'}};if(!best?.eligible)x.negativeResults.push({at,family:f,status:'FAIL',reason:'Ingen variant klarade låsta Gen3-minimikrav'});x.status='WALK_FORWARD_RUNNING';save(x);let ev;try{ev=await persistEvidence(f,x.familyResults[f],at)}catch(e){ev={status:'FROZEN · VÄNTAR PÅ SYNK',syncError:String(e?.message||e)}}x=load();x.familyResults[f].evidence=ev;if(FAMILIES.every(q=>x.familyResults[q]))x.status='WALK_FORWARD_COMPLETE';save(x);return x.familyResults[f]}
function gateChecks(r){return[
 {id:'trades',label:'Affärer',pass:r.n>=SPEC.selection.minimumOOSTrades,value:r.n,rule:'≥ '+SPEC.selection.minimumOOSTrades},
 {id:'pf',label:'PF',pass:r.pf>=SPEC.selection.profitFactor,value:Number(r.pf||0).toFixed(2),rule:'≥ '+SPEC.selection.profitFactor.toFixed(2)},
 {id:'dd',label:'DD',pass:Math.abs(r.dd)<=SPEC.selection.maxDrawdown,value:(Math.abs(r.dd||0)*100).toFixed(1)+' %',rule:'≤ '+(SPEC.selection.maxDrawdown*100).toFixed(0)+' %'},
 {id:'oos',label:'OOS-resultat',pass:r.pl>0,value:Number(r.pl||0).toFixed(0),rule:'> 0'},
 {id:'concentration',label:'Koncentration',pass:r.maxSymbolGrossProfitShare<=SPEC.selection.maxSingleSymbolGrossProfitShare,value:(Number(r.maxSymbolGrossProfitShare||0)*100).toFixed(1)+' %',rule:'≤ '+(SPEC.selection.maxSingleSymbolGrossProfitShare*100).toFixed(0)+' %'},
 {id:'folds',label:'Positiva folds',pass:r.positiveFolds>=SPEC.selection.minimumPositiveFolds,value:(r.positiveFolds||0)+'/4',rule:'≥ '+SPEC.selection.minimumPositiveFolds+'/4'}
]}
function summary(){const x=load();if(!x||!FAMILIES.every(f=>x.familyResults?.[f]))return null;const families=FAMILIES.map(f=>{const z=x.familyResults[f],r=z.best.oos,checks=gateChecks(r);return{family:f,status:z.status,trials:z.trials,params:z.best.params,score:z.best.score,oos:r,checks,failReasons:checks.filter(c=>!c.pass).map(c=>`${c.label}: ${c.value} (krav ${c.rule})`),evidence:z.evidence}});const eligible=families.filter(f=>f.status==='PASS'&&f.checks.every(c=>c.pass));return{schema:'LINA-GEN3-RESEARCH-SUMMARY-1',release:VERSION,planHash:PLAN_HASH,runnerSpecHash:RUNNER_SPEC_HASH,observedHistory:'2020-01-01 → 2024-12-31',forwardStart:'2026-09-18',tradeEnabled:false,families,eligibleCount:eligible.length,eligibleFamilies:eligible.map(x=>x.family),decision:eligible.length?'CANDIDATE_SELECTION_AVAILABLE':'NO_CANDIDATE_FOR_FORWARD',forwardOpened:false}}
async function freezeSummary(){let x=load();const sm=summary();if(!sm)throw Error('Alla fyra Gen3-familjer måste vara färdiga först');if(x.summaryFreeze?.frozen)return x.summaryFreeze;const at=new Date().toISOString(),artifact={...sm,createdAt:at,immutable:true,note:'Observerad Gen3-forskning. Ingen omkörning eller rescue. Forward får endast öppnas för kvalificerad kandidat.'};let ev={status:'LOKALT FRYST · VÄNTAR PÅ GITHUB'};const E=window.LinaEvidence;if(E?.stage&&E?.approveAndSync){const name=`LINAS_GEN3_RESEARCH_SUMMARY_${at.slice(0,10)}.json`,item=E.stage(name,JSON.stringify(artifact,null,2),'application/json','Lina Gen3');if(item?.id){try{const r=await E.approveAndSync(item.id);ev={status:r?.status||'FROZEN',name,githubPath:r?.githubPath||null,githubCommit:r?.githubCommit||null}}catch(e){ev={status:'FROZEN · VÄNTAR PÅ SYNK',syncError:String(e?.message||e)}}}}x=load();x.summaryFreeze={frozen:true,frozenAt:at,decision:sm.decision,eligibleCount:sm.eligibleCount,evidence:ev};x.status=sm.eligibleCount?'RESEARCH_FROZEN_CANDIDATE_SELECTION_AVAILABLE':'GEN3_RESEARCH_COMPLETE_NO_CANDIDATE';x.forwardOpened=false;save(x);return x.summaryFreeze}
window.LinaGen3Engine={VERSION,PLAN_HASH,RUNNER_SPEC_HASH,SPEC,FOLDS,FAMILIES,load,init,lockRunnerSpec,preflight,runFamily,gateChecks,summary,freezeSummary};
})();
